# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'board.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1254, 612)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.line_22 = QtGui.QFrame(self.centralwidget)
        self.line_22.setFrameShape(QtGui.QFrame.HLine)
        self.line_22.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_22.setObjectName(_fromUtf8("line_22"))
        self.verticalLayout.addWidget(self.line_22)
        self.board = QtGui.QHBoxLayout()
        self.board.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.board.setObjectName(_fromUtf8("board"))
        self.line_23 = QtGui.QFrame(self.centralwidget)
        self.line_23.setFrameShape(QtGui.QFrame.VLine)
        self.line_23.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_23.setObjectName(_fromUtf8("line_23"))
        self.board.addWidget(self.line_23)
        self.weather_and_scores = QtGui.QVBoxLayout()
        self.weather_and_scores.setObjectName(_fromUtf8("weather_and_scores"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 30))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_2.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Bright"))
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_3.addWidget(self.label_2)
        self.line_28 = QtGui.QFrame(self.centralwidget)
        self.line_28.setFrameShape(QtGui.QFrame.HLine)
        self.line_28.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_28.setObjectName(_fromUtf8("line_28"))
        self.verticalLayout_3.addWidget(self.line_28)
        self.p2_rounds_won_text = QtGui.QLabel(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.p2_rounds_won_text.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Bright"))
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.p2_rounds_won_text.setFont(font)
        self.p2_rounds_won_text.setAlignment(QtCore.Qt.AlignCenter)
        self.p2_rounds_won_text.setObjectName(_fromUtf8("p2_rounds_won_text"))
        self.verticalLayout_3.addWidget(self.p2_rounds_won_text)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.line_24 = QtGui.QFrame(self.centralwidget)
        self.line_24.setFrameShape(QtGui.QFrame.VLine)
        self.line_24.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_24.setObjectName(_fromUtf8("line_24"))
        self.horizontalLayout.addWidget(self.line_24)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(16777215, 30))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Bright"))
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_2.addWidget(self.label)
        self.line_25 = QtGui.QFrame(self.centralwidget)
        self.line_25.setFrameShape(QtGui.QFrame.HLine)
        self.line_25.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_25.setObjectName(_fromUtf8("line_25"))
        self.verticalLayout_2.addWidget(self.line_25)
        self.p2_score_text = QtGui.QLabel(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.p2_score_text.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Bright"))
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.p2_score_text.setFont(font)
        self.p2_score_text.setAlignment(QtCore.Qt.AlignCenter)
        self.p2_score_text.setObjectName(_fromUtf8("p2_score_text"))
        self.verticalLayout_2.addWidget(self.p2_score_text)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.weather_and_scores.addLayout(self.horizontalLayout)
        self.line_19 = QtGui.QFrame(self.centralwidget)
        self.line_19.setMinimumSize(QtCore.QSize(200, 0))
        self.line_19.setFrameShape(QtGui.QFrame.HLine)
        self.line_19.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_19.setObjectName(_fromUtf8("line_19"))
        self.weather_and_scores.addWidget(self.line_19)
        self.weather_row = QtGui.QHBoxLayout()
        self.weather_row.setObjectName(_fromUtf8("weather_row"))
        self.weather_1 = QtGui.QLabel(self.centralwidget)
        self.weather_1.setMinimumSize(QtCore.QSize(0, 100))
        self.weather_1.setText(_fromUtf8(""))
        self.weather_1.setAlignment(QtCore.Qt.AlignCenter)
        self.weather_1.setObjectName(_fromUtf8("weather_1"))
        self.weather_row.addWidget(self.weather_1)
        self.line_20 = QtGui.QFrame(self.centralwidget)
        self.line_20.setMinimumSize(QtCore.QSize(0, 100))
        self.line_20.setFrameShape(QtGui.QFrame.VLine)
        self.line_20.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_20.setObjectName(_fromUtf8("line_20"))
        self.weather_row.addWidget(self.line_20)
        self.weather_2 = QtGui.QLabel(self.centralwidget)
        self.weather_2.setText(_fromUtf8(""))
        self.weather_2.setAlignment(QtCore.Qt.AlignCenter)
        self.weather_2.setObjectName(_fromUtf8("weather_2"))
        self.weather_row.addWidget(self.weather_2)
        self.weather_and_scores.addLayout(self.weather_row)
        self.line_18 = QtGui.QFrame(self.centralwidget)
        self.line_18.setFrameShape(QtGui.QFrame.HLine)
        self.line_18.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_18.setObjectName(_fromUtf8("line_18"))
        self.weather_and_scores.addWidget(self.line_18)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 30))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_6.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Bright"))
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_4.addWidget(self.label_6)
        self.line_27 = QtGui.QFrame(self.centralwidget)
        self.line_27.setFrameShape(QtGui.QFrame.HLine)
        self.line_27.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_27.setObjectName(_fromUtf8("line_27"))
        self.verticalLayout_4.addWidget(self.line_27)
        self.p1_rounds_won_text = QtGui.QLabel(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.p1_rounds_won_text.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Bright"))
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.p1_rounds_won_text.setFont(font)
        self.p1_rounds_won_text.setAlignment(QtCore.Qt.AlignCenter)
        self.p1_rounds_won_text.setObjectName(_fromUtf8("p1_rounds_won_text"))
        self.verticalLayout_4.addWidget(self.p1_rounds_won_text)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.line_29 = QtGui.QFrame(self.centralwidget)
        self.line_29.setFrameShape(QtGui.QFrame.VLine)
        self.line_29.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_29.setObjectName(_fromUtf8("line_29"))
        self.horizontalLayout_2.addWidget(self.line_29)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 30))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_5.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Bright"))
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_5.addWidget(self.label_5)
        self.line_26 = QtGui.QFrame(self.centralwidget)
        self.line_26.setFrameShape(QtGui.QFrame.HLine)
        self.line_26.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_26.setObjectName(_fromUtf8("line_26"))
        self.verticalLayout_5.addWidget(self.line_26)
        self.p1_score_text = QtGui.QLabel(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.p1_score_text.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Bright"))
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.p1_score_text.setFont(font)
        self.p1_score_text.setAlignment(QtCore.Qt.AlignCenter)
        self.p1_score_text.setObjectName(_fromUtf8("p1_score_text"))
        self.verticalLayout_5.addWidget(self.p1_score_text)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.weather_and_scores.addLayout(self.horizontalLayout_2)
        self.board.addLayout(self.weather_and_scores)
        self.line_8 = QtGui.QFrame(self.centralwidget)
        self.line_8.setFrameShape(QtGui.QFrame.VLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.board.addWidget(self.line_8)
        self.card_area = QtGui.QVBoxLayout()
        self.card_area.setObjectName(_fromUtf8("card_area"))
        self.p2_siege_row = QtGui.QHBoxLayout()
        self.p2_siege_row.setObjectName(_fromUtf8("p2_siege_row"))
        self.p2_siege_score_text = QtGui.QLabel(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.p2_siege_score_text.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Bright"))
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.p2_siege_score_text.setFont(font)
        self.p2_siege_score_text.setObjectName(_fromUtf8("p2_siege_score_text"))
        self.p2_siege_row.addWidget(self.p2_siege_score_text)
        self.line_9 = QtGui.QFrame(self.centralwidget)
        self.line_9.setMinimumSize(QtCore.QSize(0, 50))
        self.line_9.setFrameShape(QtGui.QFrame.VLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.p2_siege_row.addWidget(self.line_9)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.p2_siege_row.addItem(spacerItem)
        self.p2_siege_row01 = QtGui.QPushButton(self.centralwidget)
        self.p2_siege_row01.setEnabled(False)
        self.p2_siege_row01.setText(_fromUtf8(""))
        self.p2_siege_row01.setIconSize(QtCore.QSize(50, 94))
        self.p2_siege_row01.setFlat(True)
        self.p2_siege_row01.setObjectName(_fromUtf8("p2_siege_row01"))
        self.p2_siege_row.addWidget(self.p2_siege_row01)
        self.p2_siege_row02 = QtGui.QPushButton(self.centralwidget)
        self.p2_siege_row02.setEnabled(False)
        self.p2_siege_row02.setText(_fromUtf8(""))
        self.p2_siege_row02.setIconSize(QtCore.QSize(50, 94))
        self.p2_siege_row02.setFlat(True)
        self.p2_siege_row02.setObjectName(_fromUtf8("p2_siege_row02"))
        self.p2_siege_row.addWidget(self.p2_siege_row02)
        self.p2_siege_row03 = QtGui.QPushButton(self.centralwidget)
        self.p2_siege_row03.setEnabled(False)
        self.p2_siege_row03.setText(_fromUtf8(""))
        self.p2_siege_row03.setIconSize(QtCore.QSize(50, 94))
        self.p2_siege_row03.setFlat(True)
        self.p2_siege_row03.setObjectName(_fromUtf8("p2_siege_row03"))
        self.p2_siege_row.addWidget(self.p2_siege_row03)
        self.p2_siege_row04 = QtGui.QPushButton(self.centralwidget)
        self.p2_siege_row04.setEnabled(False)
        self.p2_siege_row04.setText(_fromUtf8(""))
        self.p2_siege_row04.setIconSize(QtCore.QSize(50, 94))
        self.p2_siege_row04.setFlat(True)
        self.p2_siege_row04.setObjectName(_fromUtf8("p2_siege_row04"))
        self.p2_siege_row.addWidget(self.p2_siege_row04)
        self.p2_siege_row05 = QtGui.QPushButton(self.centralwidget)
        self.p2_siege_row05.setEnabled(False)
        self.p2_siege_row05.setText(_fromUtf8(""))
        self.p2_siege_row05.setIconSize(QtCore.QSize(50, 94))
        self.p2_siege_row05.setFlat(True)
        self.p2_siege_row05.setObjectName(_fromUtf8("p2_siege_row05"))
        self.p2_siege_row.addWidget(self.p2_siege_row05)
        self.p2_siege_row06 = QtGui.QPushButton(self.centralwidget)
        self.p2_siege_row06.setEnabled(False)
        self.p2_siege_row06.setText(_fromUtf8(""))
        self.p2_siege_row06.setIconSize(QtCore.QSize(50, 94))
        self.p2_siege_row06.setFlat(True)
        self.p2_siege_row06.setObjectName(_fromUtf8("p2_siege_row06"))
        self.p2_siege_row.addWidget(self.p2_siege_row06)
        self.p2_siege_row07 = QtGui.QPushButton(self.centralwidget)
        self.p2_siege_row07.setEnabled(False)
        self.p2_siege_row07.setText(_fromUtf8(""))
        self.p2_siege_row07.setIconSize(QtCore.QSize(50, 94))
        self.p2_siege_row07.setFlat(True)
        self.p2_siege_row07.setObjectName(_fromUtf8("p2_siege_row07"))
        self.p2_siege_row.addWidget(self.p2_siege_row07)
        self.p2_siege_row08 = QtGui.QPushButton(self.centralwidget)
        self.p2_siege_row08.setEnabled(False)
        self.p2_siege_row08.setText(_fromUtf8(""))
        self.p2_siege_row08.setIconSize(QtCore.QSize(50, 94))
        self.p2_siege_row08.setFlat(True)
        self.p2_siege_row08.setObjectName(_fromUtf8("p2_siege_row08"))
        self.p2_siege_row.addWidget(self.p2_siege_row08)
        self.p2_siege_row09 = QtGui.QPushButton(self.centralwidget)
        self.p2_siege_row09.setEnabled(False)
        self.p2_siege_row09.setText(_fromUtf8(""))
        self.p2_siege_row09.setIconSize(QtCore.QSize(50, 94))
        self.p2_siege_row09.setFlat(True)
        self.p2_siege_row09.setObjectName(_fromUtf8("p2_siege_row09"))
        self.p2_siege_row.addWidget(self.p2_siege_row09)
        self.p2_siege_row10 = QtGui.QPushButton(self.centralwidget)
        self.p2_siege_row10.setEnabled(False)
        self.p2_siege_row10.setText(_fromUtf8(""))
        self.p2_siege_row10.setIconSize(QtCore.QSize(50, 94))
        self.p2_siege_row10.setFlat(True)
        self.p2_siege_row10.setObjectName(_fromUtf8("p2_siege_row10"))
        self.p2_siege_row.addWidget(self.p2_siege_row10)
        self.p2_siege_row11 = QtGui.QPushButton(self.centralwidget)
        self.p2_siege_row11.setEnabled(False)
        self.p2_siege_row11.setText(_fromUtf8(""))
        self.p2_siege_row11.setIconSize(QtCore.QSize(50, 94))
        self.p2_siege_row11.setFlat(True)
        self.p2_siege_row11.setObjectName(_fromUtf8("p2_siege_row11"))
        self.p2_siege_row.addWidget(self.p2_siege_row11)
        self.p2_siege_row12 = QtGui.QPushButton(self.centralwidget)
        self.p2_siege_row12.setEnabled(False)
        self.p2_siege_row12.setText(_fromUtf8(""))
        self.p2_siege_row12.setIconSize(QtCore.QSize(50, 94))
        self.p2_siege_row12.setFlat(True)
        self.p2_siege_row12.setObjectName(_fromUtf8("p2_siege_row12"))
        self.p2_siege_row.addWidget(self.p2_siege_row12)
        self.p2_siege_row13 = QtGui.QPushButton(self.centralwidget)
        self.p2_siege_row13.setEnabled(False)
        self.p2_siege_row13.setText(_fromUtf8(""))
        self.p2_siege_row13.setIconSize(QtCore.QSize(50, 94))
        self.p2_siege_row13.setFlat(True)
        self.p2_siege_row13.setObjectName(_fromUtf8("p2_siege_row13"))
        self.p2_siege_row.addWidget(self.p2_siege_row13)
        self.p2_siege_row14 = QtGui.QPushButton(self.centralwidget)
        self.p2_siege_row14.setEnabled(False)
        self.p2_siege_row14.setText(_fromUtf8(""))
        self.p2_siege_row14.setIconSize(QtCore.QSize(50, 94))
        self.p2_siege_row14.setFlat(True)
        self.p2_siege_row14.setObjectName(_fromUtf8("p2_siege_row14"))
        self.p2_siege_row.addWidget(self.p2_siege_row14)
        self.p2_siege_row15 = QtGui.QPushButton(self.centralwidget)
        self.p2_siege_row15.setEnabled(False)
        self.p2_siege_row15.setText(_fromUtf8(""))
        self.p2_siege_row15.setIconSize(QtCore.QSize(50, 94))
        self.p2_siege_row15.setFlat(True)
        self.p2_siege_row15.setObjectName(_fromUtf8("p2_siege_row15"))
        self.p2_siege_row.addWidget(self.p2_siege_row15)
        self.p2_siege_row16 = QtGui.QPushButton(self.centralwidget)
        self.p2_siege_row16.setEnabled(False)
        self.p2_siege_row16.setText(_fromUtf8(""))
        self.p2_siege_row16.setIconSize(QtCore.QSize(50, 94))
        self.p2_siege_row16.setFlat(True)
        self.p2_siege_row16.setObjectName(_fromUtf8("p2_siege_row16"))
        self.p2_siege_row.addWidget(self.p2_siege_row16)
        self.p2_siege_row17 = QtGui.QPushButton(self.centralwidget)
        self.p2_siege_row17.setEnabled(False)
        self.p2_siege_row17.setText(_fromUtf8(""))
        self.p2_siege_row17.setIconSize(QtCore.QSize(50, 94))
        self.p2_siege_row17.setFlat(True)
        self.p2_siege_row17.setObjectName(_fromUtf8("p2_siege_row17"))
        self.p2_siege_row.addWidget(self.p2_siege_row17)
        self.p2_siege_row18 = QtGui.QPushButton(self.centralwidget)
        self.p2_siege_row18.setEnabled(False)
        self.p2_siege_row18.setText(_fromUtf8(""))
        self.p2_siege_row18.setIconSize(QtCore.QSize(50, 94))
        self.p2_siege_row18.setFlat(True)
        self.p2_siege_row18.setObjectName(_fromUtf8("p2_siege_row18"))
        self.p2_siege_row.addWidget(self.p2_siege_row18)
        self.p2_siege_row19 = QtGui.QPushButton(self.centralwidget)
        self.p2_siege_row19.setEnabled(False)
        self.p2_siege_row19.setText(_fromUtf8(""))
        self.p2_siege_row19.setIconSize(QtCore.QSize(50, 94))
        self.p2_siege_row19.setFlat(True)
        self.p2_siege_row19.setObjectName(_fromUtf8("p2_siege_row19"))
        self.p2_siege_row.addWidget(self.p2_siege_row19)
        self.p2_siege_row20 = QtGui.QPushButton(self.centralwidget)
        self.p2_siege_row20.setEnabled(False)
        self.p2_siege_row20.setText(_fromUtf8(""))
        self.p2_siege_row20.setIconSize(QtCore.QSize(50, 94))
        self.p2_siege_row20.setFlat(True)
        self.p2_siege_row20.setObjectName(_fromUtf8("p2_siege_row20"))
        self.p2_siege_row.addWidget(self.p2_siege_row20)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.p2_siege_row.addItem(spacerItem1)
        self.card_area.addLayout(self.p2_siege_row)
        self.line_7 = QtGui.QFrame(self.centralwidget)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.card_area.addWidget(self.line_7)
        self.p2_ranged_row = QtGui.QHBoxLayout()
        self.p2_ranged_row.setObjectName(_fromUtf8("p2_ranged_row"))
        self.p2_ranged_score_text = QtGui.QLabel(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.p2_ranged_score_text.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Bright"))
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.p2_ranged_score_text.setFont(font)
        self.p2_ranged_score_text.setObjectName(_fromUtf8("p2_ranged_score_text"))
        self.p2_ranged_row.addWidget(self.p2_ranged_score_text)
        self.line_10 = QtGui.QFrame(self.centralwidget)
        self.line_10.setMinimumSize(QtCore.QSize(0, 50))
        self.line_10.setFrameShape(QtGui.QFrame.VLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName(_fromUtf8("line_10"))
        self.p2_ranged_row.addWidget(self.line_10)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.p2_ranged_row.addItem(spacerItem2)
        self.p2_ranged_row01 = QtGui.QPushButton(self.centralwidget)
        self.p2_ranged_row01.setEnabled(False)
        self.p2_ranged_row01.setText(_fromUtf8(""))
        self.p2_ranged_row01.setIconSize(QtCore.QSize(50, 94))
        self.p2_ranged_row01.setFlat(True)
        self.p2_ranged_row01.setObjectName(_fromUtf8("p2_ranged_row01"))
        self.p2_ranged_row.addWidget(self.p2_ranged_row01)
        self.p2_ranged_row02 = QtGui.QPushButton(self.centralwidget)
        self.p2_ranged_row02.setEnabled(False)
        self.p2_ranged_row02.setText(_fromUtf8(""))
        self.p2_ranged_row02.setIconSize(QtCore.QSize(50, 94))
        self.p2_ranged_row02.setFlat(True)
        self.p2_ranged_row02.setObjectName(_fromUtf8("p2_ranged_row02"))
        self.p2_ranged_row.addWidget(self.p2_ranged_row02)
        self.p2_ranged_row03 = QtGui.QPushButton(self.centralwidget)
        self.p2_ranged_row03.setEnabled(False)
        self.p2_ranged_row03.setText(_fromUtf8(""))
        self.p2_ranged_row03.setIconSize(QtCore.QSize(50, 94))
        self.p2_ranged_row03.setFlat(True)
        self.p2_ranged_row03.setObjectName(_fromUtf8("p2_ranged_row03"))
        self.p2_ranged_row.addWidget(self.p2_ranged_row03)
        self.p2_ranged_row04 = QtGui.QPushButton(self.centralwidget)
        self.p2_ranged_row04.setEnabled(False)
        self.p2_ranged_row04.setText(_fromUtf8(""))
        self.p2_ranged_row04.setIconSize(QtCore.QSize(50, 94))
        self.p2_ranged_row04.setFlat(True)
        self.p2_ranged_row04.setObjectName(_fromUtf8("p2_ranged_row04"))
        self.p2_ranged_row.addWidget(self.p2_ranged_row04)
        self.p2_ranged_row05 = QtGui.QPushButton(self.centralwidget)
        self.p2_ranged_row05.setEnabled(False)
        self.p2_ranged_row05.setText(_fromUtf8(""))
        self.p2_ranged_row05.setIconSize(QtCore.QSize(50, 94))
        self.p2_ranged_row05.setFlat(True)
        self.p2_ranged_row05.setObjectName(_fromUtf8("p2_ranged_row05"))
        self.p2_ranged_row.addWidget(self.p2_ranged_row05)
        self.p2_ranged_row06 = QtGui.QPushButton(self.centralwidget)
        self.p2_ranged_row06.setEnabled(False)
        self.p2_ranged_row06.setText(_fromUtf8(""))
        self.p2_ranged_row06.setIconSize(QtCore.QSize(50, 94))
        self.p2_ranged_row06.setFlat(True)
        self.p2_ranged_row06.setObjectName(_fromUtf8("p2_ranged_row06"))
        self.p2_ranged_row.addWidget(self.p2_ranged_row06)
        self.p2_ranged_row07 = QtGui.QPushButton(self.centralwidget)
        self.p2_ranged_row07.setEnabled(False)
        self.p2_ranged_row07.setText(_fromUtf8(""))
        self.p2_ranged_row07.setIconSize(QtCore.QSize(50, 94))
        self.p2_ranged_row07.setFlat(True)
        self.p2_ranged_row07.setObjectName(_fromUtf8("p2_ranged_row07"))
        self.p2_ranged_row.addWidget(self.p2_ranged_row07)
        self.p2_ranged_row08 = QtGui.QPushButton(self.centralwidget)
        self.p2_ranged_row08.setEnabled(False)
        self.p2_ranged_row08.setText(_fromUtf8(""))
        self.p2_ranged_row08.setIconSize(QtCore.QSize(50, 94))
        self.p2_ranged_row08.setFlat(True)
        self.p2_ranged_row08.setObjectName(_fromUtf8("p2_ranged_row08"))
        self.p2_ranged_row.addWidget(self.p2_ranged_row08)
        self.p2_ranged_row09 = QtGui.QPushButton(self.centralwidget)
        self.p2_ranged_row09.setEnabled(False)
        self.p2_ranged_row09.setText(_fromUtf8(""))
        self.p2_ranged_row09.setIconSize(QtCore.QSize(50, 94))
        self.p2_ranged_row09.setFlat(True)
        self.p2_ranged_row09.setObjectName(_fromUtf8("p2_ranged_row09"))
        self.p2_ranged_row.addWidget(self.p2_ranged_row09)
        self.p2_ranged_row10 = QtGui.QPushButton(self.centralwidget)
        self.p2_ranged_row10.setEnabled(False)
        self.p2_ranged_row10.setText(_fromUtf8(""))
        self.p2_ranged_row10.setIconSize(QtCore.QSize(50, 94))
        self.p2_ranged_row10.setFlat(True)
        self.p2_ranged_row10.setObjectName(_fromUtf8("p2_ranged_row10"))
        self.p2_ranged_row.addWidget(self.p2_ranged_row10)
        self.p2_ranged_row11 = QtGui.QPushButton(self.centralwidget)
        self.p2_ranged_row11.setEnabled(False)
        self.p2_ranged_row11.setText(_fromUtf8(""))
        self.p2_ranged_row11.setIconSize(QtCore.QSize(50, 94))
        self.p2_ranged_row11.setFlat(True)
        self.p2_ranged_row11.setObjectName(_fromUtf8("p2_ranged_row11"))
        self.p2_ranged_row.addWidget(self.p2_ranged_row11)
        self.p2_ranged_row12 = QtGui.QPushButton(self.centralwidget)
        self.p2_ranged_row12.setEnabled(False)
        self.p2_ranged_row12.setText(_fromUtf8(""))
        self.p2_ranged_row12.setIconSize(QtCore.QSize(50, 94))
        self.p2_ranged_row12.setFlat(True)
        self.p2_ranged_row12.setObjectName(_fromUtf8("p2_ranged_row12"))
        self.p2_ranged_row.addWidget(self.p2_ranged_row12)
        self.p2_ranged_row13 = QtGui.QPushButton(self.centralwidget)
        self.p2_ranged_row13.setEnabled(False)
        self.p2_ranged_row13.setText(_fromUtf8(""))
        self.p2_ranged_row13.setIconSize(QtCore.QSize(50, 94))
        self.p2_ranged_row13.setFlat(True)
        self.p2_ranged_row13.setObjectName(_fromUtf8("p2_ranged_row13"))
        self.p2_ranged_row.addWidget(self.p2_ranged_row13)
        self.p2_ranged_row14 = QtGui.QPushButton(self.centralwidget)
        self.p2_ranged_row14.setEnabled(False)
        self.p2_ranged_row14.setText(_fromUtf8(""))
        self.p2_ranged_row14.setIconSize(QtCore.QSize(50, 94))
        self.p2_ranged_row14.setFlat(True)
        self.p2_ranged_row14.setObjectName(_fromUtf8("p2_ranged_row14"))
        self.p2_ranged_row.addWidget(self.p2_ranged_row14)
        self.p2_ranged_row15 = QtGui.QPushButton(self.centralwidget)
        self.p2_ranged_row15.setEnabled(False)
        self.p2_ranged_row15.setText(_fromUtf8(""))
        self.p2_ranged_row15.setIconSize(QtCore.QSize(50, 94))
        self.p2_ranged_row15.setFlat(True)
        self.p2_ranged_row15.setObjectName(_fromUtf8("p2_ranged_row15"))
        self.p2_ranged_row.addWidget(self.p2_ranged_row15)
        self.p2_ranged_row16 = QtGui.QPushButton(self.centralwidget)
        self.p2_ranged_row16.setEnabled(False)
        self.p2_ranged_row16.setText(_fromUtf8(""))
        self.p2_ranged_row16.setIconSize(QtCore.QSize(50, 94))
        self.p2_ranged_row16.setFlat(True)
        self.p2_ranged_row16.setObjectName(_fromUtf8("p2_ranged_row16"))
        self.p2_ranged_row.addWidget(self.p2_ranged_row16)
        self.p2_ranged_row17 = QtGui.QPushButton(self.centralwidget)
        self.p2_ranged_row17.setEnabled(False)
        self.p2_ranged_row17.setText(_fromUtf8(""))
        self.p2_ranged_row17.setIconSize(QtCore.QSize(50, 94))
        self.p2_ranged_row17.setFlat(True)
        self.p2_ranged_row17.setObjectName(_fromUtf8("p2_ranged_row17"))
        self.p2_ranged_row.addWidget(self.p2_ranged_row17)
        self.p2_ranged_row18 = QtGui.QPushButton(self.centralwidget)
        self.p2_ranged_row18.setEnabled(False)
        self.p2_ranged_row18.setText(_fromUtf8(""))
        self.p2_ranged_row18.setIconSize(QtCore.QSize(50, 94))
        self.p2_ranged_row18.setFlat(True)
        self.p2_ranged_row18.setObjectName(_fromUtf8("p2_ranged_row18"))
        self.p2_ranged_row.addWidget(self.p2_ranged_row18)
        self.p2_ranged_row19 = QtGui.QPushButton(self.centralwidget)
        self.p2_ranged_row19.setEnabled(False)
        self.p2_ranged_row19.setText(_fromUtf8(""))
        self.p2_ranged_row19.setIconSize(QtCore.QSize(50, 94))
        self.p2_ranged_row19.setFlat(True)
        self.p2_ranged_row19.setObjectName(_fromUtf8("p2_ranged_row19"))
        self.p2_ranged_row.addWidget(self.p2_ranged_row19)
        self.p2_ranged_row20 = QtGui.QPushButton(self.centralwidget)
        self.p2_ranged_row20.setEnabled(False)
        self.p2_ranged_row20.setText(_fromUtf8(""))
        self.p2_ranged_row20.setIconSize(QtCore.QSize(50, 94))
        self.p2_ranged_row20.setFlat(True)
        self.p2_ranged_row20.setObjectName(_fromUtf8("p2_ranged_row20"))
        self.p2_ranged_row.addWidget(self.p2_ranged_row20)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.p2_ranged_row.addItem(spacerItem3)
        self.card_area.addLayout(self.p2_ranged_row)
        self.line_6 = QtGui.QFrame(self.centralwidget)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.card_area.addWidget(self.line_6)
        self.p2_melee_row = QtGui.QHBoxLayout()
        self.p2_melee_row.setObjectName(_fromUtf8("p2_melee_row"))
        self.p2_melee_score_text = QtGui.QLabel(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.p2_melee_score_text.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Bright"))
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.p2_melee_score_text.setFont(font)
        self.p2_melee_score_text.setObjectName(_fromUtf8("p2_melee_score_text"))
        self.p2_melee_row.addWidget(self.p2_melee_score_text)
        self.line_11 = QtGui.QFrame(self.centralwidget)
        self.line_11.setMinimumSize(QtCore.QSize(0, 50))
        self.line_11.setFrameShape(QtGui.QFrame.VLine)
        self.line_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_11.setObjectName(_fromUtf8("line_11"))
        self.p2_melee_row.addWidget(self.line_11)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.p2_melee_row.addItem(spacerItem4)
        self.p2_melee_row01 = QtGui.QPushButton(self.centralwidget)
        self.p2_melee_row01.setEnabled(False)
        self.p2_melee_row01.setText(_fromUtf8(""))
        self.p2_melee_row01.setIconSize(QtCore.QSize(50, 94))
        self.p2_melee_row01.setFlat(True)
        self.p2_melee_row01.setObjectName(_fromUtf8("p2_melee_row01"))
        self.p2_melee_row.addWidget(self.p2_melee_row01)
        self.p2_melee_row02 = QtGui.QPushButton(self.centralwidget)
        self.p2_melee_row02.setEnabled(False)
        self.p2_melee_row02.setText(_fromUtf8(""))
        self.p2_melee_row02.setIconSize(QtCore.QSize(50, 94))
        self.p2_melee_row02.setFlat(True)
        self.p2_melee_row02.setObjectName(_fromUtf8("p2_melee_row02"))
        self.p2_melee_row.addWidget(self.p2_melee_row02)
        self.p2_melee_row03 = QtGui.QPushButton(self.centralwidget)
        self.p2_melee_row03.setEnabled(False)
        self.p2_melee_row03.setText(_fromUtf8(""))
        self.p2_melee_row03.setIconSize(QtCore.QSize(50, 94))
        self.p2_melee_row03.setFlat(True)
        self.p2_melee_row03.setObjectName(_fromUtf8("p2_melee_row03"))
        self.p2_melee_row.addWidget(self.p2_melee_row03)
        self.p2_melee_row04 = QtGui.QPushButton(self.centralwidget)
        self.p2_melee_row04.setEnabled(False)
        self.p2_melee_row04.setText(_fromUtf8(""))
        self.p2_melee_row04.setIconSize(QtCore.QSize(50, 94))
        self.p2_melee_row04.setFlat(True)
        self.p2_melee_row04.setObjectName(_fromUtf8("p2_melee_row04"))
        self.p2_melee_row.addWidget(self.p2_melee_row04)
        self.p2_melee_row05 = QtGui.QPushButton(self.centralwidget)
        self.p2_melee_row05.setEnabled(False)
        self.p2_melee_row05.setText(_fromUtf8(""))
        self.p2_melee_row05.setIconSize(QtCore.QSize(50, 94))
        self.p2_melee_row05.setFlat(True)
        self.p2_melee_row05.setObjectName(_fromUtf8("p2_melee_row05"))
        self.p2_melee_row.addWidget(self.p2_melee_row05)
        self.p2_melee_row06 = QtGui.QPushButton(self.centralwidget)
        self.p2_melee_row06.setEnabled(False)
        self.p2_melee_row06.setText(_fromUtf8(""))
        self.p2_melee_row06.setIconSize(QtCore.QSize(50, 94))
        self.p2_melee_row06.setFlat(True)
        self.p2_melee_row06.setObjectName(_fromUtf8("p2_melee_row06"))
        self.p2_melee_row.addWidget(self.p2_melee_row06)
        self.p2_melee_row07 = QtGui.QPushButton(self.centralwidget)
        self.p2_melee_row07.setEnabled(False)
        self.p2_melee_row07.setText(_fromUtf8(""))
        self.p2_melee_row07.setIconSize(QtCore.QSize(50, 94))
        self.p2_melee_row07.setFlat(True)
        self.p2_melee_row07.setObjectName(_fromUtf8("p2_melee_row07"))
        self.p2_melee_row.addWidget(self.p2_melee_row07)
        self.p2_melee_row08 = QtGui.QPushButton(self.centralwidget)
        self.p2_melee_row08.setEnabled(False)
        self.p2_melee_row08.setText(_fromUtf8(""))
        self.p2_melee_row08.setIconSize(QtCore.QSize(50, 94))
        self.p2_melee_row08.setFlat(True)
        self.p2_melee_row08.setObjectName(_fromUtf8("p2_melee_row08"))
        self.p2_melee_row.addWidget(self.p2_melee_row08)
        self.p2_melee_row09 = QtGui.QPushButton(self.centralwidget)
        self.p2_melee_row09.setEnabled(False)
        self.p2_melee_row09.setText(_fromUtf8(""))
        self.p2_melee_row09.setIconSize(QtCore.QSize(50, 94))
        self.p2_melee_row09.setFlat(True)
        self.p2_melee_row09.setObjectName(_fromUtf8("p2_melee_row09"))
        self.p2_melee_row.addWidget(self.p2_melee_row09)
        self.p2_melee_row10 = QtGui.QPushButton(self.centralwidget)
        self.p2_melee_row10.setEnabled(False)
        self.p2_melee_row10.setText(_fromUtf8(""))
        self.p2_melee_row10.setIconSize(QtCore.QSize(50, 94))
        self.p2_melee_row10.setFlat(True)
        self.p2_melee_row10.setObjectName(_fromUtf8("p2_melee_row10"))
        self.p2_melee_row.addWidget(self.p2_melee_row10)
        self.p2_melee_row11 = QtGui.QPushButton(self.centralwidget)
        self.p2_melee_row11.setEnabled(False)
        self.p2_melee_row11.setText(_fromUtf8(""))
        self.p2_melee_row11.setIconSize(QtCore.QSize(50, 94))
        self.p2_melee_row11.setFlat(True)
        self.p2_melee_row11.setObjectName(_fromUtf8("p2_melee_row11"))
        self.p2_melee_row.addWidget(self.p2_melee_row11)
        self.p2_melee_row12 = QtGui.QPushButton(self.centralwidget)
        self.p2_melee_row12.setEnabled(False)
        self.p2_melee_row12.setText(_fromUtf8(""))
        self.p2_melee_row12.setIconSize(QtCore.QSize(50, 94))
        self.p2_melee_row12.setFlat(True)
        self.p2_melee_row12.setObjectName(_fromUtf8("p2_melee_row12"))
        self.p2_melee_row.addWidget(self.p2_melee_row12)
        self.p2_melee_row13 = QtGui.QPushButton(self.centralwidget)
        self.p2_melee_row13.setEnabled(False)
        self.p2_melee_row13.setText(_fromUtf8(""))
        self.p2_melee_row13.setIconSize(QtCore.QSize(50, 94))
        self.p2_melee_row13.setFlat(True)
        self.p2_melee_row13.setObjectName(_fromUtf8("p2_melee_row13"))
        self.p2_melee_row.addWidget(self.p2_melee_row13)
        self.p2_melee_row14 = QtGui.QPushButton(self.centralwidget)
        self.p2_melee_row14.setEnabled(False)
        self.p2_melee_row14.setText(_fromUtf8(""))
        self.p2_melee_row14.setIconSize(QtCore.QSize(50, 94))
        self.p2_melee_row14.setFlat(True)
        self.p2_melee_row14.setObjectName(_fromUtf8("p2_melee_row14"))
        self.p2_melee_row.addWidget(self.p2_melee_row14)
        self.p2_melee_row15 = QtGui.QPushButton(self.centralwidget)
        self.p2_melee_row15.setEnabled(False)
        self.p2_melee_row15.setText(_fromUtf8(""))
        self.p2_melee_row15.setIconSize(QtCore.QSize(50, 94))
        self.p2_melee_row15.setFlat(True)
        self.p2_melee_row15.setObjectName(_fromUtf8("p2_melee_row15"))
        self.p2_melee_row.addWidget(self.p2_melee_row15)
        self.p2_melee_row16 = QtGui.QPushButton(self.centralwidget)
        self.p2_melee_row16.setEnabled(False)
        self.p2_melee_row16.setText(_fromUtf8(""))
        self.p2_melee_row16.setIconSize(QtCore.QSize(50, 94))
        self.p2_melee_row16.setFlat(True)
        self.p2_melee_row16.setObjectName(_fromUtf8("p2_melee_row16"))
        self.p2_melee_row.addWidget(self.p2_melee_row16)
        self.p2_melee_row17 = QtGui.QPushButton(self.centralwidget)
        self.p2_melee_row17.setEnabled(False)
        self.p2_melee_row17.setText(_fromUtf8(""))
        self.p2_melee_row17.setIconSize(QtCore.QSize(50, 94))
        self.p2_melee_row17.setFlat(True)
        self.p2_melee_row17.setObjectName(_fromUtf8("p2_melee_row17"))
        self.p2_melee_row.addWidget(self.p2_melee_row17)
        self.p2_melee_row18 = QtGui.QPushButton(self.centralwidget)
        self.p2_melee_row18.setEnabled(False)
        self.p2_melee_row18.setText(_fromUtf8(""))
        self.p2_melee_row18.setIconSize(QtCore.QSize(50, 94))
        self.p2_melee_row18.setFlat(True)
        self.p2_melee_row18.setObjectName(_fromUtf8("p2_melee_row18"))
        self.p2_melee_row.addWidget(self.p2_melee_row18)
        self.p2_melee_row19 = QtGui.QPushButton(self.centralwidget)
        self.p2_melee_row19.setEnabled(False)
        self.p2_melee_row19.setText(_fromUtf8(""))
        self.p2_melee_row19.setIconSize(QtCore.QSize(50, 94))
        self.p2_melee_row19.setFlat(True)
        self.p2_melee_row19.setObjectName(_fromUtf8("p2_melee_row19"))
        self.p2_melee_row.addWidget(self.p2_melee_row19)
        self.p2_melee_row20 = QtGui.QPushButton(self.centralwidget)
        self.p2_melee_row20.setEnabled(False)
        self.p2_melee_row20.setText(_fromUtf8(""))
        self.p2_melee_row20.setIconSize(QtCore.QSize(50, 94))
        self.p2_melee_row20.setFlat(True)
        self.p2_melee_row20.setObjectName(_fromUtf8("p2_melee_row20"))
        self.p2_melee_row.addWidget(self.p2_melee_row20)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.p2_melee_row.addItem(spacerItem5)
        self.card_area.addLayout(self.p2_melee_row)
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.card_area.addWidget(self.line_2)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.card_area.addWidget(self.line)
        self.p1_melee_row = QtGui.QHBoxLayout()
        self.p1_melee_row.setObjectName(_fromUtf8("p1_melee_row"))
        self.p1_melee_score_text = QtGui.QLabel(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.p1_melee_score_text.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Bright"))
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.p1_melee_score_text.setFont(font)
        self.p1_melee_score_text.setObjectName(_fromUtf8("p1_melee_score_text"))
        self.p1_melee_row.addWidget(self.p1_melee_score_text)
        self.line_12 = QtGui.QFrame(self.centralwidget)
        self.line_12.setMinimumSize(QtCore.QSize(0, 50))
        self.line_12.setFrameShape(QtGui.QFrame.VLine)
        self.line_12.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_12.setObjectName(_fromUtf8("line_12"))
        self.p1_melee_row.addWidget(self.line_12)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.p1_melee_row.addItem(spacerItem6)
        self.p1_melee_row01 = QtGui.QPushButton(self.centralwidget)
        self.p1_melee_row01.setEnabled(False)
        self.p1_melee_row01.setText(_fromUtf8(""))
        self.p1_melee_row01.setIconSize(QtCore.QSize(50, 94))
        self.p1_melee_row01.setFlat(True)
        self.p1_melee_row01.setObjectName(_fromUtf8("p1_melee_row01"))
        self.p1_melee_row.addWidget(self.p1_melee_row01)
        self.p1_melee_row02 = QtGui.QPushButton(self.centralwidget)
        self.p1_melee_row02.setEnabled(False)
        self.p1_melee_row02.setText(_fromUtf8(""))
        self.p1_melee_row02.setIconSize(QtCore.QSize(50, 94))
        self.p1_melee_row02.setFlat(True)
        self.p1_melee_row02.setObjectName(_fromUtf8("p1_melee_row02"))
        self.p1_melee_row.addWidget(self.p1_melee_row02)
        self.p1_melee_row03 = QtGui.QPushButton(self.centralwidget)
        self.p1_melee_row03.setEnabled(False)
        self.p1_melee_row03.setText(_fromUtf8(""))
        self.p1_melee_row03.setIconSize(QtCore.QSize(50, 94))
        self.p1_melee_row03.setFlat(True)
        self.p1_melee_row03.setObjectName(_fromUtf8("p1_melee_row03"))
        self.p1_melee_row.addWidget(self.p1_melee_row03)
        self.p1_melee_row04 = QtGui.QPushButton(self.centralwidget)
        self.p1_melee_row04.setEnabled(False)
        self.p1_melee_row04.setText(_fromUtf8(""))
        self.p1_melee_row04.setIconSize(QtCore.QSize(50, 94))
        self.p1_melee_row04.setFlat(True)
        self.p1_melee_row04.setObjectName(_fromUtf8("p1_melee_row04"))
        self.p1_melee_row.addWidget(self.p1_melee_row04)
        self.p1_melee_row05 = QtGui.QPushButton(self.centralwidget)
        self.p1_melee_row05.setEnabled(False)
        self.p1_melee_row05.setText(_fromUtf8(""))
        self.p1_melee_row05.setIconSize(QtCore.QSize(50, 94))
        self.p1_melee_row05.setFlat(True)
        self.p1_melee_row05.setObjectName(_fromUtf8("p1_melee_row05"))
        self.p1_melee_row.addWidget(self.p1_melee_row05)
        self.p1_melee_row06 = QtGui.QPushButton(self.centralwidget)
        self.p1_melee_row06.setEnabled(False)
        self.p1_melee_row06.setText(_fromUtf8(""))
        self.p1_melee_row06.setIconSize(QtCore.QSize(50, 94))
        self.p1_melee_row06.setFlat(True)
        self.p1_melee_row06.setObjectName(_fromUtf8("p1_melee_row06"))
        self.p1_melee_row.addWidget(self.p1_melee_row06)
        self.p1_melee_row07 = QtGui.QPushButton(self.centralwidget)
        self.p1_melee_row07.setEnabled(False)
        self.p1_melee_row07.setText(_fromUtf8(""))
        self.p1_melee_row07.setIconSize(QtCore.QSize(50, 94))
        self.p1_melee_row07.setFlat(True)
        self.p1_melee_row07.setObjectName(_fromUtf8("p1_melee_row07"))
        self.p1_melee_row.addWidget(self.p1_melee_row07)
        self.p1_melee_row08 = QtGui.QPushButton(self.centralwidget)
        self.p1_melee_row08.setEnabled(False)
        self.p1_melee_row08.setText(_fromUtf8(""))
        self.p1_melee_row08.setIconSize(QtCore.QSize(50, 94))
        self.p1_melee_row08.setFlat(True)
        self.p1_melee_row08.setObjectName(_fromUtf8("p1_melee_row08"))
        self.p1_melee_row.addWidget(self.p1_melee_row08)
        self.p1_melee_row09 = QtGui.QPushButton(self.centralwidget)
        self.p1_melee_row09.setEnabled(False)
        self.p1_melee_row09.setText(_fromUtf8(""))
        self.p1_melee_row09.setIconSize(QtCore.QSize(50, 94))
        self.p1_melee_row09.setFlat(True)
        self.p1_melee_row09.setObjectName(_fromUtf8("p1_melee_row09"))
        self.p1_melee_row.addWidget(self.p1_melee_row09)
        self.p1_melee_row10 = QtGui.QPushButton(self.centralwidget)
        self.p1_melee_row10.setEnabled(False)
        self.p1_melee_row10.setText(_fromUtf8(""))
        self.p1_melee_row10.setIconSize(QtCore.QSize(50, 94))
        self.p1_melee_row10.setFlat(True)
        self.p1_melee_row10.setObjectName(_fromUtf8("p1_melee_row10"))
        self.p1_melee_row.addWidget(self.p1_melee_row10)
        self.p1_melee_row11 = QtGui.QPushButton(self.centralwidget)
        self.p1_melee_row11.setEnabled(False)
        self.p1_melee_row11.setText(_fromUtf8(""))
        self.p1_melee_row11.setIconSize(QtCore.QSize(50, 94))
        self.p1_melee_row11.setFlat(True)
        self.p1_melee_row11.setObjectName(_fromUtf8("p1_melee_row11"))
        self.p1_melee_row.addWidget(self.p1_melee_row11)
        self.p1_melee_row12 = QtGui.QPushButton(self.centralwidget)
        self.p1_melee_row12.setEnabled(False)
        self.p1_melee_row12.setText(_fromUtf8(""))
        self.p1_melee_row12.setIconSize(QtCore.QSize(50, 94))
        self.p1_melee_row12.setFlat(True)
        self.p1_melee_row12.setObjectName(_fromUtf8("p1_melee_row12"))
        self.p1_melee_row.addWidget(self.p1_melee_row12)
        self.p1_melee_row13 = QtGui.QPushButton(self.centralwidget)
        self.p1_melee_row13.setEnabled(False)
        self.p1_melee_row13.setText(_fromUtf8(""))
        self.p1_melee_row13.setIconSize(QtCore.QSize(50, 94))
        self.p1_melee_row13.setFlat(True)
        self.p1_melee_row13.setObjectName(_fromUtf8("p1_melee_row13"))
        self.p1_melee_row.addWidget(self.p1_melee_row13)
        self.p1_melee_row14 = QtGui.QPushButton(self.centralwidget)
        self.p1_melee_row14.setEnabled(False)
        self.p1_melee_row14.setText(_fromUtf8(""))
        self.p1_melee_row14.setIconSize(QtCore.QSize(50, 94))
        self.p1_melee_row14.setFlat(True)
        self.p1_melee_row14.setObjectName(_fromUtf8("p1_melee_row14"))
        self.p1_melee_row.addWidget(self.p1_melee_row14)
        self.p1_melee_row15 = QtGui.QPushButton(self.centralwidget)
        self.p1_melee_row15.setEnabled(False)
        self.p1_melee_row15.setText(_fromUtf8(""))
        self.p1_melee_row15.setIconSize(QtCore.QSize(50, 94))
        self.p1_melee_row15.setFlat(True)
        self.p1_melee_row15.setObjectName(_fromUtf8("p1_melee_row15"))
        self.p1_melee_row.addWidget(self.p1_melee_row15)
        self.p1_melee_row16 = QtGui.QPushButton(self.centralwidget)
        self.p1_melee_row16.setEnabled(False)
        self.p1_melee_row16.setText(_fromUtf8(""))
        self.p1_melee_row16.setIconSize(QtCore.QSize(50, 94))
        self.p1_melee_row16.setFlat(True)
        self.p1_melee_row16.setObjectName(_fromUtf8("p1_melee_row16"))
        self.p1_melee_row.addWidget(self.p1_melee_row16)
        self.p1_melee_row17 = QtGui.QPushButton(self.centralwidget)
        self.p1_melee_row17.setEnabled(False)
        self.p1_melee_row17.setText(_fromUtf8(""))
        self.p1_melee_row17.setIconSize(QtCore.QSize(50, 94))
        self.p1_melee_row17.setFlat(True)
        self.p1_melee_row17.setObjectName(_fromUtf8("p1_melee_row17"))
        self.p1_melee_row.addWidget(self.p1_melee_row17)
        self.p1_melee_row18 = QtGui.QPushButton(self.centralwidget)
        self.p1_melee_row18.setEnabled(False)
        self.p1_melee_row18.setText(_fromUtf8(""))
        self.p1_melee_row18.setIconSize(QtCore.QSize(50, 94))
        self.p1_melee_row18.setFlat(True)
        self.p1_melee_row18.setObjectName(_fromUtf8("p1_melee_row18"))
        self.p1_melee_row.addWidget(self.p1_melee_row18)
        self.p1_melee_row19 = QtGui.QPushButton(self.centralwidget)
        self.p1_melee_row19.setEnabled(False)
        self.p1_melee_row19.setText(_fromUtf8(""))
        self.p1_melee_row19.setIconSize(QtCore.QSize(50, 94))
        self.p1_melee_row19.setFlat(True)
        self.p1_melee_row19.setObjectName(_fromUtf8("p1_melee_row19"))
        self.p1_melee_row.addWidget(self.p1_melee_row19)
        self.p1_melee_row20 = QtGui.QPushButton(self.centralwidget)
        self.p1_melee_row20.setEnabled(False)
        self.p1_melee_row20.setText(_fromUtf8(""))
        self.p1_melee_row20.setIconSize(QtCore.QSize(50, 94))
        self.p1_melee_row20.setFlat(True)
        self.p1_melee_row20.setObjectName(_fromUtf8("p1_melee_row20"))
        self.p1_melee_row.addWidget(self.p1_melee_row20)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.p1_melee_row.addItem(spacerItem7)
        self.card_area.addLayout(self.p1_melee_row)
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.card_area.addWidget(self.line_3)
        self.p1_ranged_row = QtGui.QHBoxLayout()
        self.p1_ranged_row.setObjectName(_fromUtf8("p1_ranged_row"))
        self.p1_ranged_score_text = QtGui.QLabel(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.p1_ranged_score_text.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Bright"))
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.p1_ranged_score_text.setFont(font)
        self.p1_ranged_score_text.setObjectName(_fromUtf8("p1_ranged_score_text"))
        self.p1_ranged_row.addWidget(self.p1_ranged_score_text)
        self.line_13 = QtGui.QFrame(self.centralwidget)
        self.line_13.setMinimumSize(QtCore.QSize(0, 50))
        self.line_13.setFrameShape(QtGui.QFrame.VLine)
        self.line_13.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_13.setObjectName(_fromUtf8("line_13"))
        self.p1_ranged_row.addWidget(self.line_13)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.p1_ranged_row.addItem(spacerItem8)
        self.p1_ranged_row01 = QtGui.QPushButton(self.centralwidget)
        self.p1_ranged_row01.setEnabled(False)
        self.p1_ranged_row01.setText(_fromUtf8(""))
        self.p1_ranged_row01.setIconSize(QtCore.QSize(50, 94))
        self.p1_ranged_row01.setFlat(True)
        self.p1_ranged_row01.setObjectName(_fromUtf8("p1_ranged_row01"))
        self.p1_ranged_row.addWidget(self.p1_ranged_row01)
        self.p1_ranged_row02 = QtGui.QPushButton(self.centralwidget)
        self.p1_ranged_row02.setEnabled(False)
        self.p1_ranged_row02.setText(_fromUtf8(""))
        self.p1_ranged_row02.setIconSize(QtCore.QSize(50, 94))
        self.p1_ranged_row02.setFlat(True)
        self.p1_ranged_row02.setObjectName(_fromUtf8("p1_ranged_row02"))
        self.p1_ranged_row.addWidget(self.p1_ranged_row02)
        self.p1_ranged_row03 = QtGui.QPushButton(self.centralwidget)
        self.p1_ranged_row03.setEnabled(False)
        self.p1_ranged_row03.setText(_fromUtf8(""))
        self.p1_ranged_row03.setIconSize(QtCore.QSize(50, 94))
        self.p1_ranged_row03.setFlat(True)
        self.p1_ranged_row03.setObjectName(_fromUtf8("p1_ranged_row03"))
        self.p1_ranged_row.addWidget(self.p1_ranged_row03)
        self.p1_ranged_row04 = QtGui.QPushButton(self.centralwidget)
        self.p1_ranged_row04.setEnabled(False)
        self.p1_ranged_row04.setText(_fromUtf8(""))
        self.p1_ranged_row04.setIconSize(QtCore.QSize(50, 94))
        self.p1_ranged_row04.setFlat(True)
        self.p1_ranged_row04.setObjectName(_fromUtf8("p1_ranged_row04"))
        self.p1_ranged_row.addWidget(self.p1_ranged_row04)
        self.p1_ranged_row05 = QtGui.QPushButton(self.centralwidget)
        self.p1_ranged_row05.setEnabled(False)
        self.p1_ranged_row05.setText(_fromUtf8(""))
        self.p1_ranged_row05.setIconSize(QtCore.QSize(50, 94))
        self.p1_ranged_row05.setFlat(True)
        self.p1_ranged_row05.setObjectName(_fromUtf8("p1_ranged_row05"))
        self.p1_ranged_row.addWidget(self.p1_ranged_row05)
        self.p1_ranged_row06 = QtGui.QPushButton(self.centralwidget)
        self.p1_ranged_row06.setEnabled(False)
        self.p1_ranged_row06.setText(_fromUtf8(""))
        self.p1_ranged_row06.setIconSize(QtCore.QSize(50, 94))
        self.p1_ranged_row06.setFlat(True)
        self.p1_ranged_row06.setObjectName(_fromUtf8("p1_ranged_row06"))
        self.p1_ranged_row.addWidget(self.p1_ranged_row06)
        self.p1_ranged_row07 = QtGui.QPushButton(self.centralwidget)
        self.p1_ranged_row07.setEnabled(False)
        self.p1_ranged_row07.setText(_fromUtf8(""))
        self.p1_ranged_row07.setIconSize(QtCore.QSize(50, 94))
        self.p1_ranged_row07.setFlat(True)
        self.p1_ranged_row07.setObjectName(_fromUtf8("p1_ranged_row07"))
        self.p1_ranged_row.addWidget(self.p1_ranged_row07)
        self.p1_ranged_row08 = QtGui.QPushButton(self.centralwidget)
        self.p1_ranged_row08.setEnabled(False)
        self.p1_ranged_row08.setText(_fromUtf8(""))
        self.p1_ranged_row08.setIconSize(QtCore.QSize(50, 94))
        self.p1_ranged_row08.setFlat(True)
        self.p1_ranged_row08.setObjectName(_fromUtf8("p1_ranged_row08"))
        self.p1_ranged_row.addWidget(self.p1_ranged_row08)
        self.p1_ranged_row09 = QtGui.QPushButton(self.centralwidget)
        self.p1_ranged_row09.setEnabled(False)
        self.p1_ranged_row09.setText(_fromUtf8(""))
        self.p1_ranged_row09.setIconSize(QtCore.QSize(50, 94))
        self.p1_ranged_row09.setFlat(True)
        self.p1_ranged_row09.setObjectName(_fromUtf8("p1_ranged_row09"))
        self.p1_ranged_row.addWidget(self.p1_ranged_row09)
        self.p1_ranged_row10 = QtGui.QPushButton(self.centralwidget)
        self.p1_ranged_row10.setEnabled(False)
        self.p1_ranged_row10.setText(_fromUtf8(""))
        self.p1_ranged_row10.setIconSize(QtCore.QSize(50, 94))
        self.p1_ranged_row10.setFlat(True)
        self.p1_ranged_row10.setObjectName(_fromUtf8("p1_ranged_row10"))
        self.p1_ranged_row.addWidget(self.p1_ranged_row10)
        self.p1_ranged_row11 = QtGui.QPushButton(self.centralwidget)
        self.p1_ranged_row11.setEnabled(False)
        self.p1_ranged_row11.setText(_fromUtf8(""))
        self.p1_ranged_row11.setIconSize(QtCore.QSize(50, 94))
        self.p1_ranged_row11.setFlat(True)
        self.p1_ranged_row11.setObjectName(_fromUtf8("p1_ranged_row11"))
        self.p1_ranged_row.addWidget(self.p1_ranged_row11)
        self.p1_ranged_row12 = QtGui.QPushButton(self.centralwidget)
        self.p1_ranged_row12.setEnabled(False)
        self.p1_ranged_row12.setText(_fromUtf8(""))
        self.p1_ranged_row12.setIconSize(QtCore.QSize(50, 94))
        self.p1_ranged_row12.setFlat(True)
        self.p1_ranged_row12.setObjectName(_fromUtf8("p1_ranged_row12"))
        self.p1_ranged_row.addWidget(self.p1_ranged_row12)
        self.p1_ranged_row13 = QtGui.QPushButton(self.centralwidget)
        self.p1_ranged_row13.setEnabled(False)
        self.p1_ranged_row13.setText(_fromUtf8(""))
        self.p1_ranged_row13.setIconSize(QtCore.QSize(50, 94))
        self.p1_ranged_row13.setFlat(True)
        self.p1_ranged_row13.setObjectName(_fromUtf8("p1_ranged_row13"))
        self.p1_ranged_row.addWidget(self.p1_ranged_row13)
        self.p1_ranged_row14 = QtGui.QPushButton(self.centralwidget)
        self.p1_ranged_row14.setEnabled(False)
        self.p1_ranged_row14.setText(_fromUtf8(""))
        self.p1_ranged_row14.setIconSize(QtCore.QSize(50, 94))
        self.p1_ranged_row14.setFlat(True)
        self.p1_ranged_row14.setObjectName(_fromUtf8("p1_ranged_row14"))
        self.p1_ranged_row.addWidget(self.p1_ranged_row14)
        self.p1_ranged_row15 = QtGui.QPushButton(self.centralwidget)
        self.p1_ranged_row15.setEnabled(False)
        self.p1_ranged_row15.setText(_fromUtf8(""))
        self.p1_ranged_row15.setIconSize(QtCore.QSize(50, 94))
        self.p1_ranged_row15.setFlat(True)
        self.p1_ranged_row15.setObjectName(_fromUtf8("p1_ranged_row15"))
        self.p1_ranged_row.addWidget(self.p1_ranged_row15)
        self.p1_ranged_row16 = QtGui.QPushButton(self.centralwidget)
        self.p1_ranged_row16.setEnabled(False)
        self.p1_ranged_row16.setText(_fromUtf8(""))
        self.p1_ranged_row16.setIconSize(QtCore.QSize(50, 94))
        self.p1_ranged_row16.setFlat(True)
        self.p1_ranged_row16.setObjectName(_fromUtf8("p1_ranged_row16"))
        self.p1_ranged_row.addWidget(self.p1_ranged_row16)
        self.p1_ranged_row17 = QtGui.QPushButton(self.centralwidget)
        self.p1_ranged_row17.setEnabled(False)
        self.p1_ranged_row17.setText(_fromUtf8(""))
        self.p1_ranged_row17.setIconSize(QtCore.QSize(50, 94))
        self.p1_ranged_row17.setFlat(True)
        self.p1_ranged_row17.setObjectName(_fromUtf8("p1_ranged_row17"))
        self.p1_ranged_row.addWidget(self.p1_ranged_row17)
        self.p1_ranged_row18 = QtGui.QPushButton(self.centralwidget)
        self.p1_ranged_row18.setEnabled(False)
        self.p1_ranged_row18.setText(_fromUtf8(""))
        self.p1_ranged_row18.setIconSize(QtCore.QSize(50, 94))
        self.p1_ranged_row18.setFlat(True)
        self.p1_ranged_row18.setObjectName(_fromUtf8("p1_ranged_row18"))
        self.p1_ranged_row.addWidget(self.p1_ranged_row18)
        self.p1_ranged_row19 = QtGui.QPushButton(self.centralwidget)
        self.p1_ranged_row19.setEnabled(False)
        self.p1_ranged_row19.setText(_fromUtf8(""))
        self.p1_ranged_row19.setIconSize(QtCore.QSize(50, 94))
        self.p1_ranged_row19.setFlat(True)
        self.p1_ranged_row19.setObjectName(_fromUtf8("p1_ranged_row19"))
        self.p1_ranged_row.addWidget(self.p1_ranged_row19)
        self.p1_ranged_row20 = QtGui.QPushButton(self.centralwidget)
        self.p1_ranged_row20.setEnabled(False)
        self.p1_ranged_row20.setText(_fromUtf8(""))
        self.p1_ranged_row20.setIconSize(QtCore.QSize(50, 94))
        self.p1_ranged_row20.setFlat(True)
        self.p1_ranged_row20.setObjectName(_fromUtf8("p1_ranged_row20"))
        self.p1_ranged_row.addWidget(self.p1_ranged_row20)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.p1_ranged_row.addItem(spacerItem9)
        self.card_area.addLayout(self.p1_ranged_row)
        self.line_4 = QtGui.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.card_area.addWidget(self.line_4)
        self.p1_siege_row = QtGui.QHBoxLayout()
        self.p1_siege_row.setObjectName(_fromUtf8("p1_siege_row"))
        self.p1_siege_score_text = QtGui.QLabel(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.p1_siege_score_text.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Bright"))
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.p1_siege_score_text.setFont(font)
        self.p1_siege_score_text.setObjectName(_fromUtf8("p1_siege_score_text"))
        self.p1_siege_row.addWidget(self.p1_siege_score_text)
        self.line_14 = QtGui.QFrame(self.centralwidget)
        self.line_14.setMinimumSize(QtCore.QSize(0, 50))
        self.line_14.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.line_14.setFrameShape(QtGui.QFrame.VLine)
        self.line_14.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_14.setObjectName(_fromUtf8("line_14"))
        self.p1_siege_row.addWidget(self.line_14)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.p1_siege_row.addItem(spacerItem10)
        self.p1_siege_row01 = QtGui.QPushButton(self.centralwidget)
        self.p1_siege_row01.setEnabled(False)
        self.p1_siege_row01.setText(_fromUtf8(""))
        self.p1_siege_row01.setIconSize(QtCore.QSize(50, 94))
        self.p1_siege_row01.setFlat(True)
        self.p1_siege_row01.setObjectName(_fromUtf8("p1_siege_row01"))
        self.p1_siege_row.addWidget(self.p1_siege_row01)
        self.p1_siege_row02 = QtGui.QPushButton(self.centralwidget)
        self.p1_siege_row02.setEnabled(False)
        self.p1_siege_row02.setText(_fromUtf8(""))
        self.p1_siege_row02.setIconSize(QtCore.QSize(50, 94))
        self.p1_siege_row02.setFlat(True)
        self.p1_siege_row02.setObjectName(_fromUtf8("p1_siege_row02"))
        self.p1_siege_row.addWidget(self.p1_siege_row02)
        self.p1_siege_row03 = QtGui.QPushButton(self.centralwidget)
        self.p1_siege_row03.setEnabled(False)
        self.p1_siege_row03.setText(_fromUtf8(""))
        self.p1_siege_row03.setIconSize(QtCore.QSize(50, 94))
        self.p1_siege_row03.setFlat(True)
        self.p1_siege_row03.setObjectName(_fromUtf8("p1_siege_row03"))
        self.p1_siege_row.addWidget(self.p1_siege_row03)
        self.p1_siege_row04 = QtGui.QPushButton(self.centralwidget)
        self.p1_siege_row04.setEnabled(False)
        self.p1_siege_row04.setText(_fromUtf8(""))
        self.p1_siege_row04.setIconSize(QtCore.QSize(50, 94))
        self.p1_siege_row04.setFlat(True)
        self.p1_siege_row04.setObjectName(_fromUtf8("p1_siege_row04"))
        self.p1_siege_row.addWidget(self.p1_siege_row04)
        self.p1_siege_row05 = QtGui.QPushButton(self.centralwidget)
        self.p1_siege_row05.setEnabled(False)
        self.p1_siege_row05.setText(_fromUtf8(""))
        self.p1_siege_row05.setIconSize(QtCore.QSize(50, 94))
        self.p1_siege_row05.setFlat(True)
        self.p1_siege_row05.setObjectName(_fromUtf8("p1_siege_row05"))
        self.p1_siege_row.addWidget(self.p1_siege_row05)
        self.p1_siege_row06 = QtGui.QPushButton(self.centralwidget)
        self.p1_siege_row06.setEnabled(False)
        self.p1_siege_row06.setText(_fromUtf8(""))
        self.p1_siege_row06.setIconSize(QtCore.QSize(50, 94))
        self.p1_siege_row06.setFlat(True)
        self.p1_siege_row06.setObjectName(_fromUtf8("p1_siege_row06"))
        self.p1_siege_row.addWidget(self.p1_siege_row06)
        self.p1_siege_row07 = QtGui.QPushButton(self.centralwidget)
        self.p1_siege_row07.setEnabled(False)
        self.p1_siege_row07.setText(_fromUtf8(""))
        self.p1_siege_row07.setIconSize(QtCore.QSize(50, 94))
        self.p1_siege_row07.setFlat(True)
        self.p1_siege_row07.setObjectName(_fromUtf8("p1_siege_row07"))
        self.p1_siege_row.addWidget(self.p1_siege_row07)
        self.p1_siege_row08 = QtGui.QPushButton(self.centralwidget)
        self.p1_siege_row08.setEnabled(False)
        self.p1_siege_row08.setText(_fromUtf8(""))
        self.p1_siege_row08.setIconSize(QtCore.QSize(50, 94))
        self.p1_siege_row08.setFlat(True)
        self.p1_siege_row08.setObjectName(_fromUtf8("p1_siege_row08"))
        self.p1_siege_row.addWidget(self.p1_siege_row08)
        self.p1_siege_row09 = QtGui.QPushButton(self.centralwidget)
        self.p1_siege_row09.setEnabled(False)
        self.p1_siege_row09.setText(_fromUtf8(""))
        self.p1_siege_row09.setIconSize(QtCore.QSize(50, 94))
        self.p1_siege_row09.setFlat(True)
        self.p1_siege_row09.setObjectName(_fromUtf8("p1_siege_row09"))
        self.p1_siege_row.addWidget(self.p1_siege_row09)
        self.p1_siege_row10 = QtGui.QPushButton(self.centralwidget)
        self.p1_siege_row10.setEnabled(False)
        self.p1_siege_row10.setText(_fromUtf8(""))
        self.p1_siege_row10.setIconSize(QtCore.QSize(50, 94))
        self.p1_siege_row10.setFlat(True)
        self.p1_siege_row10.setObjectName(_fromUtf8("p1_siege_row10"))
        self.p1_siege_row.addWidget(self.p1_siege_row10)
        self.p1_siege_row11 = QtGui.QPushButton(self.centralwidget)
        self.p1_siege_row11.setEnabled(False)
        self.p1_siege_row11.setText(_fromUtf8(""))
        self.p1_siege_row11.setIconSize(QtCore.QSize(50, 94))
        self.p1_siege_row11.setFlat(True)
        self.p1_siege_row11.setObjectName(_fromUtf8("p1_siege_row11"))
        self.p1_siege_row.addWidget(self.p1_siege_row11)
        self.p1_siege_row12 = QtGui.QPushButton(self.centralwidget)
        self.p1_siege_row12.setEnabled(False)
        self.p1_siege_row12.setText(_fromUtf8(""))
        self.p1_siege_row12.setIconSize(QtCore.QSize(50, 94))
        self.p1_siege_row12.setFlat(True)
        self.p1_siege_row12.setObjectName(_fromUtf8("p1_siege_row12"))
        self.p1_siege_row.addWidget(self.p1_siege_row12)
        self.p1_siege_row13 = QtGui.QPushButton(self.centralwidget)
        self.p1_siege_row13.setEnabled(False)
        self.p1_siege_row13.setText(_fromUtf8(""))
        self.p1_siege_row13.setIconSize(QtCore.QSize(50, 94))
        self.p1_siege_row13.setFlat(True)
        self.p1_siege_row13.setObjectName(_fromUtf8("p1_siege_row13"))
        self.p1_siege_row.addWidget(self.p1_siege_row13)
        self.p1_siege_row14 = QtGui.QPushButton(self.centralwidget)
        self.p1_siege_row14.setEnabled(False)
        self.p1_siege_row14.setText(_fromUtf8(""))
        self.p1_siege_row14.setIconSize(QtCore.QSize(50, 94))
        self.p1_siege_row14.setFlat(True)
        self.p1_siege_row14.setObjectName(_fromUtf8("p1_siege_row14"))
        self.p1_siege_row.addWidget(self.p1_siege_row14)
        self.p1_siege_row15 = QtGui.QPushButton(self.centralwidget)
        self.p1_siege_row15.setEnabled(False)
        self.p1_siege_row15.setText(_fromUtf8(""))
        self.p1_siege_row15.setIconSize(QtCore.QSize(50, 94))
        self.p1_siege_row15.setFlat(True)
        self.p1_siege_row15.setObjectName(_fromUtf8("p1_siege_row15"))
        self.p1_siege_row.addWidget(self.p1_siege_row15)
        self.p1_siege_row16 = QtGui.QPushButton(self.centralwidget)
        self.p1_siege_row16.setEnabled(False)
        self.p1_siege_row16.setText(_fromUtf8(""))
        self.p1_siege_row16.setIconSize(QtCore.QSize(50, 94))
        self.p1_siege_row16.setFlat(True)
        self.p1_siege_row16.setObjectName(_fromUtf8("p1_siege_row16"))
        self.p1_siege_row.addWidget(self.p1_siege_row16)
        self.p1_siege_row17 = QtGui.QPushButton(self.centralwidget)
        self.p1_siege_row17.setEnabled(False)
        self.p1_siege_row17.setText(_fromUtf8(""))
        self.p1_siege_row17.setIconSize(QtCore.QSize(50, 94))
        self.p1_siege_row17.setFlat(True)
        self.p1_siege_row17.setObjectName(_fromUtf8("p1_siege_row17"))
        self.p1_siege_row.addWidget(self.p1_siege_row17)
        self.p1_siege_row18 = QtGui.QPushButton(self.centralwidget)
        self.p1_siege_row18.setEnabled(False)
        self.p1_siege_row18.setText(_fromUtf8(""))
        self.p1_siege_row18.setIconSize(QtCore.QSize(50, 94))
        self.p1_siege_row18.setFlat(True)
        self.p1_siege_row18.setObjectName(_fromUtf8("p1_siege_row18"))
        self.p1_siege_row.addWidget(self.p1_siege_row18)
        self.p1_siege_row19 = QtGui.QPushButton(self.centralwidget)
        self.p1_siege_row19.setEnabled(False)
        self.p1_siege_row19.setText(_fromUtf8(""))
        self.p1_siege_row19.setIconSize(QtCore.QSize(50, 94))
        self.p1_siege_row19.setFlat(True)
        self.p1_siege_row19.setObjectName(_fromUtf8("p1_siege_row19"))
        self.p1_siege_row.addWidget(self.p1_siege_row19)
        self.p1_siege_row20 = QtGui.QPushButton(self.centralwidget)
        self.p1_siege_row20.setEnabled(False)
        self.p1_siege_row20.setText(_fromUtf8(""))
        self.p1_siege_row20.setIconSize(QtCore.QSize(50, 94))
        self.p1_siege_row20.setFlat(True)
        self.p1_siege_row20.setObjectName(_fromUtf8("p1_siege_row20"))
        self.p1_siege_row.addWidget(self.p1_siege_row20)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.p1_siege_row.addItem(spacerItem11)
        self.card_area.addLayout(self.p1_siege_row)
        self.board.addLayout(self.card_area)
        self.line_21 = QtGui.QFrame(self.centralwidget)
        self.line_21.setFrameShape(QtGui.QFrame.VLine)
        self.line_21.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_21.setObjectName(_fromUtf8("line_21"))
        self.board.addWidget(self.line_21)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setContentsMargins(10, -1, 10, -1)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.passButton = QtGui.QPushButton(self.centralwidget)
        self.passButton.setEnabled(False)
        self.passButton.setObjectName(_fromUtf8("passButton"))
        self.verticalLayout_8.addWidget(self.passButton)
        self.nextButton = QtGui.QPushButton(self.centralwidget)
        self.nextButton.setEnabled(False)
        self.nextButton.setObjectName(_fromUtf8("nextButton"))
        self.verticalLayout_8.addWidget(self.nextButton)
        self.meleeButton = QtGui.QPushButton(self.centralwidget)
        self.meleeButton.setEnabled(False)
        self.meleeButton.setObjectName(_fromUtf8("meleeButton"))
        self.verticalLayout_8.addWidget(self.meleeButton)
        self.rangedButton = QtGui.QPushButton(self.centralwidget)
        self.rangedButton.setEnabled(False)
        self.rangedButton.setObjectName(_fromUtf8("rangedButton"))
        self.verticalLayout_8.addWidget(self.rangedButton)
        self.siegeButton = QtGui.QPushButton(self.centralwidget)
        self.siegeButton.setEnabled(False)
        self.siegeButton.setObjectName(_fromUtf8("siegeButton"))
        self.verticalLayout_8.addWidget(self.siegeButton)
        self.board.addLayout(self.verticalLayout_8)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.deckListBox = QtGui.QListWidget(self.centralwidget)
        self.deckListBox.setObjectName(_fromUtf8("deckListBox"))
        self.verticalLayout_6.addWidget(self.deckListBox)
        self.selectDeck = QtGui.QPushButton(self.centralwidget)
        self.selectDeck.setObjectName(_fromUtf8("selectDeck"))
        self.verticalLayout_6.addWidget(self.selectDeck)
        self.board.addLayout(self.verticalLayout_6)
        self.line_30 = QtGui.QFrame(self.centralwidget)
        self.line_30.setFrameShape(QtGui.QFrame.VLine)
        self.line_30.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_30.setObjectName(_fromUtf8("line_30"))
        self.board.addWidget(self.line_30)
        self.verticalLayout.addLayout(self.board)
        self.line_31 = QtGui.QFrame(self.centralwidget)
        self.line_31.setFrameShape(QtGui.QFrame.HLine)
        self.line_31.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_31.setObjectName(_fromUtf8("line_31"))
        self.verticalLayout.addWidget(self.line_31)
        self.gameMessage = QtGui.QLabel(self.centralwidget)
        self.gameMessage.setMaximumSize(QtCore.QSize(16777215, 50))
        self.gameMessage.setAlignment(QtCore.Qt.AlignCenter)
        self.gameMessage.setObjectName(_fromUtf8("gameMessage"))
        self.verticalLayout.addWidget(self.gameMessage)
        self.line_5 = QtGui.QFrame(self.centralwidget)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.verticalLayout.addWidget(self.line_5)
        self.hand = QtGui.QHBoxLayout()
        self.hand.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.hand.setObjectName(_fromUtf8("hand"))
        self.line_15 = QtGui.QFrame(self.centralwidget)
        self.line_15.setMinimumSize(QtCore.QSize(0, 100))
        self.line_15.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.line_15.setFrameShape(QtGui.QFrame.VLine)
        self.line_15.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_15.setObjectName(_fromUtf8("line_15"))
        self.hand.addWidget(self.line_15)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hand.addItem(spacerItem12)
        self.hand_01 = QtGui.QPushButton(self.centralwidget)
        self.hand_01.setEnabled(False)
        self.hand_01.setText(_fromUtf8(""))
        self.hand_01.setIconSize(QtCore.QSize(100, 188))
        self.hand_01.setFlat(True)
        self.hand_01.setObjectName(_fromUtf8("hand_01"))
        self.hand.addWidget(self.hand_01)
        self.hand_02 = QtGui.QPushButton(self.centralwidget)
        self.hand_02.setEnabled(False)
        self.hand_02.setText(_fromUtf8(""))
        self.hand_02.setIconSize(QtCore.QSize(100, 188))
        self.hand_02.setFlat(True)
        self.hand_02.setObjectName(_fromUtf8("hand_02"))
        self.hand.addWidget(self.hand_02)
        self.hand_03 = QtGui.QPushButton(self.centralwidget)
        self.hand_03.setEnabled(False)
        self.hand_03.setText(_fromUtf8(""))
        self.hand_03.setIconSize(QtCore.QSize(100, 188))
        self.hand_03.setFlat(True)
        self.hand_03.setObjectName(_fromUtf8("hand_03"))
        self.hand.addWidget(self.hand_03)
        self.hand_04 = QtGui.QPushButton(self.centralwidget)
        self.hand_04.setEnabled(False)
        self.hand_04.setText(_fromUtf8(""))
        self.hand_04.setIconSize(QtCore.QSize(100, 188))
        self.hand_04.setFlat(True)
        self.hand_04.setObjectName(_fromUtf8("hand_04"))
        self.hand.addWidget(self.hand_04)
        self.hand_05 = QtGui.QPushButton(self.centralwidget)
        self.hand_05.setEnabled(False)
        self.hand_05.setText(_fromUtf8(""))
        self.hand_05.setIconSize(QtCore.QSize(100, 188))
        self.hand_05.setFlat(True)
        self.hand_05.setObjectName(_fromUtf8("hand_05"))
        self.hand.addWidget(self.hand_05)
        self.hand_06 = QtGui.QPushButton(self.centralwidget)
        self.hand_06.setEnabled(False)
        self.hand_06.setText(_fromUtf8(""))
        self.hand_06.setIconSize(QtCore.QSize(100, 188))
        self.hand_06.setFlat(True)
        self.hand_06.setObjectName(_fromUtf8("hand_06"))
        self.hand.addWidget(self.hand_06)
        self.hand_07 = QtGui.QPushButton(self.centralwidget)
        self.hand_07.setEnabled(False)
        self.hand_07.setText(_fromUtf8(""))
        self.hand_07.setIconSize(QtCore.QSize(100, 188))
        self.hand_07.setFlat(True)
        self.hand_07.setObjectName(_fromUtf8("hand_07"))
        self.hand.addWidget(self.hand_07)
        self.hand_08 = QtGui.QPushButton(self.centralwidget)
        self.hand_08.setEnabled(False)
        self.hand_08.setText(_fromUtf8(""))
        self.hand_08.setIconSize(QtCore.QSize(100, 188))
        self.hand_08.setFlat(True)
        self.hand_08.setObjectName(_fromUtf8("hand_08"))
        self.hand.addWidget(self.hand_08)
        self.hand_09 = QtGui.QPushButton(self.centralwidget)
        self.hand_09.setEnabled(False)
        self.hand_09.setText(_fromUtf8(""))
        self.hand_09.setIconSize(QtCore.QSize(100, 188))
        self.hand_09.setFlat(True)
        self.hand_09.setObjectName(_fromUtf8("hand_09"))
        self.hand.addWidget(self.hand_09)
        self.hand_10 = QtGui.QPushButton(self.centralwidget)
        self.hand_10.setEnabled(False)
        self.hand_10.setText(_fromUtf8(""))
        self.hand_10.setIconSize(QtCore.QSize(100, 188))
        self.hand_10.setFlat(True)
        self.hand_10.setObjectName(_fromUtf8("hand_10"))
        self.hand.addWidget(self.hand_10)
        self.hand_11 = QtGui.QPushButton(self.centralwidget)
        self.hand_11.setEnabled(False)
        self.hand_11.setText(_fromUtf8(""))
        self.hand_11.setIconSize(QtCore.QSize(100, 188))
        self.hand_11.setFlat(True)
        self.hand_11.setObjectName(_fromUtf8("hand_11"))
        self.hand.addWidget(self.hand_11)
        self.hand_12 = QtGui.QPushButton(self.centralwidget)
        self.hand_12.setEnabled(False)
        self.hand_12.setText(_fromUtf8(""))
        self.hand_12.setIconSize(QtCore.QSize(100, 188))
        self.hand_12.setFlat(True)
        self.hand_12.setObjectName(_fromUtf8("hand_12"))
        self.hand.addWidget(self.hand_12)
        self.hand_13 = QtGui.QPushButton(self.centralwidget)
        self.hand_13.setEnabled(False)
        self.hand_13.setText(_fromUtf8(""))
        self.hand_13.setIconSize(QtCore.QSize(100, 188))
        self.hand_13.setFlat(True)
        self.hand_13.setObjectName(_fromUtf8("hand_13"))
        self.hand.addWidget(self.hand_13)
        self.hand_14 = QtGui.QPushButton(self.centralwidget)
        self.hand_14.setEnabled(False)
        self.hand_14.setText(_fromUtf8(""))
        self.hand_14.setIconSize(QtCore.QSize(100, 188))
        self.hand_14.setFlat(True)
        self.hand_14.setObjectName(_fromUtf8("hand_14"))
        self.hand.addWidget(self.hand_14)
        self.hand_15 = QtGui.QPushButton(self.centralwidget)
        self.hand_15.setEnabled(False)
        self.hand_15.setText(_fromUtf8(""))
        self.hand_15.setIconSize(QtCore.QSize(100, 188))
        self.hand_15.setFlat(True)
        self.hand_15.setObjectName(_fromUtf8("hand_15"))
        self.hand.addWidget(self.hand_15)
        self.hand_16 = QtGui.QPushButton(self.centralwidget)
        self.hand_16.setEnabled(False)
        self.hand_16.setText(_fromUtf8(""))
        self.hand_16.setIconSize(QtCore.QSize(100, 188))
        self.hand_16.setFlat(True)
        self.hand_16.setObjectName(_fromUtf8("hand_16"))
        self.hand.addWidget(self.hand_16)
        self.hand_17 = QtGui.QPushButton(self.centralwidget)
        self.hand_17.setEnabled(False)
        self.hand_17.setText(_fromUtf8(""))
        self.hand_17.setIconSize(QtCore.QSize(100, 188))
        self.hand_17.setFlat(True)
        self.hand_17.setObjectName(_fromUtf8("hand_17"))
        self.hand.addWidget(self.hand_17)
        self.hand_18 = QtGui.QPushButton(self.centralwidget)
        self.hand_18.setEnabled(False)
        self.hand_18.setText(_fromUtf8(""))
        self.hand_18.setIconSize(QtCore.QSize(100, 188))
        self.hand_18.setFlat(True)
        self.hand_18.setObjectName(_fromUtf8("hand_18"))
        self.hand.addWidget(self.hand_18)
        self.hand_19 = QtGui.QPushButton(self.centralwidget)
        self.hand_19.setEnabled(False)
        self.hand_19.setText(_fromUtf8(""))
        self.hand_19.setIconSize(QtCore.QSize(100, 188))
        self.hand_19.setFlat(True)
        self.hand_19.setObjectName(_fromUtf8("hand_19"))
        self.hand.addWidget(self.hand_19)
        self.hand_20 = QtGui.QPushButton(self.centralwidget)
        self.hand_20.setEnabled(False)
        self.hand_20.setText(_fromUtf8(""))
        self.hand_20.setIconSize(QtCore.QSize(100, 188))
        self.hand_20.setFlat(True)
        self.hand_20.setObjectName(_fromUtf8("hand_20"))
        self.hand.addWidget(self.hand_20)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hand.addItem(spacerItem13)
        self.line_16 = QtGui.QFrame(self.centralwidget)
        self.line_16.setFrameShape(QtGui.QFrame.VLine)
        self.line_16.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_16.setObjectName(_fromUtf8("line_16"))
        self.hand.addWidget(self.line_16)
        self.verticalLayout.addLayout(self.hand)
        self.line_17 = QtGui.QFrame(self.centralwidget)
        self.line_17.setFrameShape(QtGui.QFrame.HLine)
        self.line_17.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_17.setObjectName(_fromUtf8("line_17"))
        self.verticalLayout.addWidget(self.line_17)
        self.graveyard = QtGui.QHBoxLayout()
        self.graveyard.setContentsMargins(-1, 0, -1, -1)
        self.graveyard.setObjectName(_fromUtf8("graveyard"))
        spacerItem14 = QtGui.QSpacerItem(40, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.graveyard.addItem(spacerItem14)
        self.grave_01 = QtGui.QPushButton(self.centralwidget)
        self.grave_01.setEnabled(False)
        self.grave_01.setText(_fromUtf8(""))
        self.grave_01.setIconSize(QtCore.QSize(100, 188))
        self.grave_01.setFlat(True)
        self.grave_01.setObjectName(_fromUtf8("grave_01"))
        self.graveyard.addWidget(self.grave_01)
        self.grave_02 = QtGui.QPushButton(self.centralwidget)
        self.grave_02.setEnabled(False)
        self.grave_02.setText(_fromUtf8(""))
        self.grave_02.setIconSize(QtCore.QSize(100, 188))
        self.grave_02.setFlat(True)
        self.grave_02.setObjectName(_fromUtf8("grave_02"))
        self.graveyard.addWidget(self.grave_02)
        self.grave_03 = QtGui.QPushButton(self.centralwidget)
        self.grave_03.setEnabled(False)
        self.grave_03.setText(_fromUtf8(""))
        self.grave_03.setIconSize(QtCore.QSize(100, 188))
        self.grave_03.setFlat(True)
        self.grave_03.setObjectName(_fromUtf8("grave_03"))
        self.graveyard.addWidget(self.grave_03)
        self.grave_04 = QtGui.QPushButton(self.centralwidget)
        self.grave_04.setEnabled(False)
        self.grave_04.setText(_fromUtf8(""))
        self.grave_04.setIconSize(QtCore.QSize(100, 188))
        self.grave_04.setFlat(True)
        self.grave_04.setObjectName(_fromUtf8("grave_04"))
        self.graveyard.addWidget(self.grave_04)
        self.grave_05 = QtGui.QPushButton(self.centralwidget)
        self.grave_05.setEnabled(False)
        self.grave_05.setText(_fromUtf8(""))
        self.grave_05.setIconSize(QtCore.QSize(100, 188))
        self.grave_05.setFlat(True)
        self.grave_05.setObjectName(_fromUtf8("grave_05"))
        self.graveyard.addWidget(self.grave_05)
        self.grave_06 = QtGui.QPushButton(self.centralwidget)
        self.grave_06.setEnabled(False)
        self.grave_06.setText(_fromUtf8(""))
        self.grave_06.setIconSize(QtCore.QSize(100, 188))
        self.grave_06.setFlat(True)
        self.grave_06.setObjectName(_fromUtf8("grave_06"))
        self.graveyard.addWidget(self.grave_06)
        self.grave_07 = QtGui.QPushButton(self.centralwidget)
        self.grave_07.setEnabled(False)
        self.grave_07.setText(_fromUtf8(""))
        self.grave_07.setIconSize(QtCore.QSize(100, 188))
        self.grave_07.setFlat(True)
        self.grave_07.setObjectName(_fromUtf8("grave_07"))
        self.graveyard.addWidget(self.grave_07)
        self.grave_08 = QtGui.QPushButton(self.centralwidget)
        self.grave_08.setEnabled(False)
        self.grave_08.setText(_fromUtf8(""))
        self.grave_08.setIconSize(QtCore.QSize(100, 188))
        self.grave_08.setFlat(True)
        self.grave_08.setObjectName(_fromUtf8("grave_08"))
        self.graveyard.addWidget(self.grave_08)
        self.grave_09 = QtGui.QPushButton(self.centralwidget)
        self.grave_09.setEnabled(False)
        self.grave_09.setText(_fromUtf8(""))
        self.grave_09.setIconSize(QtCore.QSize(100, 188))
        self.grave_09.setFlat(True)
        self.grave_09.setObjectName(_fromUtf8("grave_09"))
        self.graveyard.addWidget(self.grave_09)
        self.grave_10 = QtGui.QPushButton(self.centralwidget)
        self.grave_10.setEnabled(False)
        self.grave_10.setText(_fromUtf8(""))
        self.grave_10.setIconSize(QtCore.QSize(100, 188))
        self.grave_10.setFlat(True)
        self.grave_10.setObjectName(_fromUtf8("grave_10"))
        self.graveyard.addWidget(self.grave_10)
        self.grave_11 = QtGui.QPushButton(self.centralwidget)
        self.grave_11.setEnabled(False)
        self.grave_11.setText(_fromUtf8(""))
        self.grave_11.setIconSize(QtCore.QSize(100, 188))
        self.grave_11.setFlat(True)
        self.grave_11.setObjectName(_fromUtf8("grave_11"))
        self.graveyard.addWidget(self.grave_11)
        self.grave_12 = QtGui.QPushButton(self.centralwidget)
        self.grave_12.setEnabled(False)
        self.grave_12.setText(_fromUtf8(""))
        self.grave_12.setIconSize(QtCore.QSize(100, 188))
        self.grave_12.setFlat(True)
        self.grave_12.setObjectName(_fromUtf8("grave_12"))
        self.graveyard.addWidget(self.grave_12)
        self.grave_13 = QtGui.QPushButton(self.centralwidget)
        self.grave_13.setEnabled(False)
        self.grave_13.setText(_fromUtf8(""))
        self.grave_13.setIconSize(QtCore.QSize(100, 188))
        self.grave_13.setFlat(True)
        self.grave_13.setObjectName(_fromUtf8("grave_13"))
        self.graveyard.addWidget(self.grave_13)
        self.grave_14 = QtGui.QPushButton(self.centralwidget)
        self.grave_14.setEnabled(False)
        self.grave_14.setText(_fromUtf8(""))
        self.grave_14.setIconSize(QtCore.QSize(100, 188))
        self.grave_14.setFlat(True)
        self.grave_14.setObjectName(_fromUtf8("grave_14"))
        self.graveyard.addWidget(self.grave_14)
        self.grave_15 = QtGui.QPushButton(self.centralwidget)
        self.grave_15.setEnabled(False)
        self.grave_15.setText(_fromUtf8(""))
        self.grave_15.setIconSize(QtCore.QSize(100, 188))
        self.grave_15.setFlat(True)
        self.grave_15.setObjectName(_fromUtf8("grave_15"))
        self.graveyard.addWidget(self.grave_15)
        self.grave_16 = QtGui.QPushButton(self.centralwidget)
        self.grave_16.setEnabled(False)
        self.grave_16.setText(_fromUtf8(""))
        self.grave_16.setIconSize(QtCore.QSize(100, 188))
        self.grave_16.setFlat(True)
        self.grave_16.setObjectName(_fromUtf8("grave_16"))
        self.graveyard.addWidget(self.grave_16)
        self.grave_17 = QtGui.QPushButton(self.centralwidget)
        self.grave_17.setEnabled(False)
        self.grave_17.setText(_fromUtf8(""))
        self.grave_17.setIconSize(QtCore.QSize(100, 188))
        self.grave_17.setFlat(True)
        self.grave_17.setObjectName(_fromUtf8("grave_17"))
        self.graveyard.addWidget(self.grave_17)
        self.grave_18 = QtGui.QPushButton(self.centralwidget)
        self.grave_18.setEnabled(False)
        self.grave_18.setText(_fromUtf8(""))
        self.grave_18.setIconSize(QtCore.QSize(100, 188))
        self.grave_18.setFlat(True)
        self.grave_18.setObjectName(_fromUtf8("grave_18"))
        self.graveyard.addWidget(self.grave_18)
        self.grave_19 = QtGui.QPushButton(self.centralwidget)
        self.grave_19.setEnabled(False)
        self.grave_19.setText(_fromUtf8(""))
        self.grave_19.setIconSize(QtCore.QSize(100, 188))
        self.grave_19.setFlat(True)
        self.grave_19.setObjectName(_fromUtf8("grave_19"))
        self.graveyard.addWidget(self.grave_19)
        self.grave_20 = QtGui.QPushButton(self.centralwidget)
        self.grave_20.setEnabled(False)
        self.grave_20.setText(_fromUtf8(""))
        self.grave_20.setIconSize(QtCore.QSize(100, 188))
        self.grave_20.setFlat(True)
        self.grave_20.setObjectName(_fromUtf8("grave_20"))
        self.graveyard.addWidget(self.grave_20)
        spacerItem15 = QtGui.QSpacerItem(40, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.graveyard.addItem(spacerItem15)
        self.verticalLayout.addLayout(self.graveyard)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Jwent", None))
        self.label_2.setText(_translate("MainWindow", "Rounds Won", None))
        self.p2_rounds_won_text.setText(_translate("MainWindow", "0", None))
        self.label.setText(_translate("MainWindow", "Score", None))
        self.p2_score_text.setText(_translate("MainWindow", "0", None))
        self.label_6.setText(_translate("MainWindow", "Rounds Won", None))
        self.p1_rounds_won_text.setText(_translate("MainWindow", "0", None))
        self.label_5.setText(_translate("MainWindow", "Score", None))
        self.p1_score_text.setText(_translate("MainWindow", "0", None))
        self.p2_siege_score_text.setText(_translate("MainWindow", "0", None))
        self.p2_ranged_score_text.setText(_translate("MainWindow", "0", None))
        self.p2_melee_score_text.setText(_translate("MainWindow", "0", None))
        self.p1_melee_score_text.setText(_translate("MainWindow", "0", None))
        self.p1_ranged_score_text.setText(_translate("MainWindow", "0", None))
        self.p1_siege_score_text.setText(_translate("MainWindow", "0", None))
        self.passButton.setText(_translate("MainWindow", "Pass", None))
        self.nextButton.setText(_translate("MainWindow", "Next", None))
        self.meleeButton.setText(_translate("MainWindow", "Melee", None))
        self.rangedButton.setText(_translate("MainWindow", "Ranged", None))
        self.siegeButton.setText(_translate("MainWindow", "Siege", None))
        self.selectDeck.setText(_translate("MainWindow", "Select Deck", None))
        self.gameMessage.setText(_translate("MainWindow", "Select decks", None))

