# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'board.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1019, 568)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.board = QtGui.QHBoxLayout()
        self.board.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.board.setObjectName(_fromUtf8("board"))
        self.weather_and_scores = QtGui.QVBoxLayout()
        self.weather_and_scores.setObjectName(_fromUtf8("weather_and_scores"))
        self.p2_score_text = QtGui.QLabel(self.centralwidget)
        self.p2_score_text.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.p2_score_text.setObjectName(_fromUtf8("p2_score_text"))
        self.weather_and_scores.addWidget(self.p2_score_text)
        self.weather_row = QtGui.QHBoxLayout()
        self.weather_row.setObjectName(_fromUtf8("weather_row"))
        self.weather_1 = QtGui.QLabel(self.centralwidget)
        self.weather_1.setText(_fromUtf8(""))
        self.weather_1.setAlignment(QtCore.Qt.AlignCenter)
        self.weather_1.setObjectName(_fromUtf8("weather_1"))
        self.weather_row.addWidget(self.weather_1)
        self.weather_2 = QtGui.QLabel(self.centralwidget)
        self.weather_2.setText(_fromUtf8(""))
        self.weather_2.setAlignment(QtCore.Qt.AlignCenter)
        self.weather_2.setObjectName(_fromUtf8("weather_2"))
        self.weather_row.addWidget(self.weather_2)
        self.weather_and_scores.addLayout(self.weather_row)
        self.p1_score_text = QtGui.QLabel(self.centralwidget)
        self.p1_score_text.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.p1_score_text.setObjectName(_fromUtf8("p1_score_text"))
        self.weather_and_scores.addWidget(self.p1_score_text)
        self.board.addLayout(self.weather_and_scores)
        self.line_8 = QtGui.QFrame(self.centralwidget)
        self.line_8.setFrameShape(QtGui.QFrame.VLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.board.addWidget(self.line_8)
        self.card_area = QtGui.QVBoxLayout()
        self.card_area.setObjectName(_fromUtf8("card_area"))
        self.p2_siege_row = QtGui.QHBoxLayout()
        self.p2_siege_row.setObjectName(_fromUtf8("p2_siege_row"))
        self.p2_siege_score_text = QtGui.QLabel(self.centralwidget)
        self.p2_siege_score_text.setObjectName(_fromUtf8("p2_siege_score_text"))
        self.p2_siege_row.addWidget(self.p2_siege_score_text)
        self.line_9 = QtGui.QFrame(self.centralwidget)
        self.line_9.setMinimumSize(QtCore.QSize(0, 50))
        self.line_9.setFrameShape(QtGui.QFrame.VLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.p2_siege_row.addWidget(self.line_9)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.p2_siege_row.addItem(spacerItem)
        self.p2_siege_row1 = QtGui.QLabel(self.centralwidget)
        self.p2_siege_row1.setText(_fromUtf8(""))
        self.p2_siege_row1.setObjectName(_fromUtf8("p2_siege_row1"))
        self.p2_siege_row.addWidget(self.p2_siege_row1)
        self.p2_siege_row2 = QtGui.QLabel(self.centralwidget)
        self.p2_siege_row2.setText(_fromUtf8(""))
        self.p2_siege_row2.setObjectName(_fromUtf8("p2_siege_row2"))
        self.p2_siege_row.addWidget(self.p2_siege_row2)
        self.p2_siege_row3 = QtGui.QLabel(self.centralwidget)
        self.p2_siege_row3.setText(_fromUtf8(""))
        self.p2_siege_row3.setObjectName(_fromUtf8("p2_siege_row3"))
        self.p2_siege_row.addWidget(self.p2_siege_row3)
        self.p2_siege_row4 = QtGui.QLabel(self.centralwidget)
        self.p2_siege_row4.setText(_fromUtf8(""))
        self.p2_siege_row4.setObjectName(_fromUtf8("p2_siege_row4"))
        self.p2_siege_row.addWidget(self.p2_siege_row4)
        self.p2_siege_row5 = QtGui.QLabel(self.centralwidget)
        self.p2_siege_row5.setText(_fromUtf8(""))
        self.p2_siege_row5.setObjectName(_fromUtf8("p2_siege_row5"))
        self.p2_siege_row.addWidget(self.p2_siege_row5)
        self.p2_siege_row6 = QtGui.QLabel(self.centralwidget)
        self.p2_siege_row6.setText(_fromUtf8(""))
        self.p2_siege_row6.setObjectName(_fromUtf8("p2_siege_row6"))
        self.p2_siege_row.addWidget(self.p2_siege_row6)
        self.p2_siege_row7 = QtGui.QLabel(self.centralwidget)
        self.p2_siege_row7.setText(_fromUtf8(""))
        self.p2_siege_row7.setObjectName(_fromUtf8("p2_siege_row7"))
        self.p2_siege_row.addWidget(self.p2_siege_row7)
        self.p2_siege_row8 = QtGui.QLabel(self.centralwidget)
        self.p2_siege_row8.setText(_fromUtf8(""))
        self.p2_siege_row8.setObjectName(_fromUtf8("p2_siege_row8"))
        self.p2_siege_row.addWidget(self.p2_siege_row8)
        self.p2_siege_row9 = QtGui.QLabel(self.centralwidget)
        self.p2_siege_row9.setText(_fromUtf8(""))
        self.p2_siege_row9.setObjectName(_fromUtf8("p2_siege_row9"))
        self.p2_siege_row.addWidget(self.p2_siege_row9)
        self.p2_siege_row10 = QtGui.QLabel(self.centralwidget)
        self.p2_siege_row10.setText(_fromUtf8(""))
        self.p2_siege_row10.setObjectName(_fromUtf8("p2_siege_row10"))
        self.p2_siege_row.addWidget(self.p2_siege_row10)
        self.p2_siege_row11 = QtGui.QLabel(self.centralwidget)
        self.p2_siege_row11.setText(_fromUtf8(""))
        self.p2_siege_row11.setObjectName(_fromUtf8("p2_siege_row11"))
        self.p2_siege_row.addWidget(self.p2_siege_row11)
        self.p2_siege_row12 = QtGui.QLabel(self.centralwidget)
        self.p2_siege_row12.setText(_fromUtf8(""))
        self.p2_siege_row12.setObjectName(_fromUtf8("p2_siege_row12"))
        self.p2_siege_row.addWidget(self.p2_siege_row12)
        self.p2_siege_row13 = QtGui.QLabel(self.centralwidget)
        self.p2_siege_row13.setText(_fromUtf8(""))
        self.p2_siege_row13.setObjectName(_fromUtf8("p2_siege_row13"))
        self.p2_siege_row.addWidget(self.p2_siege_row13)
        self.p2_siege_row14 = QtGui.QLabel(self.centralwidget)
        self.p2_siege_row14.setText(_fromUtf8(""))
        self.p2_siege_row14.setObjectName(_fromUtf8("p2_siege_row14"))
        self.p2_siege_row.addWidget(self.p2_siege_row14)
        self.p2_siege_row15 = QtGui.QLabel(self.centralwidget)
        self.p2_siege_row15.setText(_fromUtf8(""))
        self.p2_siege_row15.setObjectName(_fromUtf8("p2_siege_row15"))
        self.p2_siege_row.addWidget(self.p2_siege_row15)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.p2_siege_row.addItem(spacerItem1)
        self.card_area.addLayout(self.p2_siege_row)
        self.line_7 = QtGui.QFrame(self.centralwidget)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.card_area.addWidget(self.line_7)
        self.p2_ranged_row = QtGui.QHBoxLayout()
        self.p2_ranged_row.setObjectName(_fromUtf8("p2_ranged_row"))
        self.p2_ranged_score_text = QtGui.QLabel(self.centralwidget)
        self.p2_ranged_score_text.setObjectName(_fromUtf8("p2_ranged_score_text"))
        self.p2_ranged_row.addWidget(self.p2_ranged_score_text)
        self.line_10 = QtGui.QFrame(self.centralwidget)
        self.line_10.setMinimumSize(QtCore.QSize(0, 50))
        self.line_10.setFrameShape(QtGui.QFrame.VLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName(_fromUtf8("line_10"))
        self.p2_ranged_row.addWidget(self.line_10)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.p2_ranged_row.addItem(spacerItem2)
        self.p2_ranged_row1 = QtGui.QLabel(self.centralwidget)
        self.p2_ranged_row1.setText(_fromUtf8(""))
        self.p2_ranged_row1.setObjectName(_fromUtf8("p2_ranged_row1"))
        self.p2_ranged_row.addWidget(self.p2_ranged_row1)
        self.p2_ranged_row2 = QtGui.QLabel(self.centralwidget)
        self.p2_ranged_row2.setText(_fromUtf8(""))
        self.p2_ranged_row2.setObjectName(_fromUtf8("p2_ranged_row2"))
        self.p2_ranged_row.addWidget(self.p2_ranged_row2)
        self.p2_ranged_row3 = QtGui.QLabel(self.centralwidget)
        self.p2_ranged_row3.setText(_fromUtf8(""))
        self.p2_ranged_row3.setObjectName(_fromUtf8("p2_ranged_row3"))
        self.p2_ranged_row.addWidget(self.p2_ranged_row3)
        self.p2_ranged_row4 = QtGui.QLabel(self.centralwidget)
        self.p2_ranged_row4.setText(_fromUtf8(""))
        self.p2_ranged_row4.setObjectName(_fromUtf8("p2_ranged_row4"))
        self.p2_ranged_row.addWidget(self.p2_ranged_row4)
        self.p2_ranged_row5 = QtGui.QLabel(self.centralwidget)
        self.p2_ranged_row5.setText(_fromUtf8(""))
        self.p2_ranged_row5.setObjectName(_fromUtf8("p2_ranged_row5"))
        self.p2_ranged_row.addWidget(self.p2_ranged_row5)
        self.p2_ranged_row6 = QtGui.QLabel(self.centralwidget)
        self.p2_ranged_row6.setText(_fromUtf8(""))
        self.p2_ranged_row6.setObjectName(_fromUtf8("p2_ranged_row6"))
        self.p2_ranged_row.addWidget(self.p2_ranged_row6)
        self.p2_ranged_row7 = QtGui.QLabel(self.centralwidget)
        self.p2_ranged_row7.setText(_fromUtf8(""))
        self.p2_ranged_row7.setObjectName(_fromUtf8("p2_ranged_row7"))
        self.p2_ranged_row.addWidget(self.p2_ranged_row7)
        self.p2_ranged_row8 = QtGui.QLabel(self.centralwidget)
        self.p2_ranged_row8.setText(_fromUtf8(""))
        self.p2_ranged_row8.setObjectName(_fromUtf8("p2_ranged_row8"))
        self.p2_ranged_row.addWidget(self.p2_ranged_row8)
        self.p2_ranged_row9 = QtGui.QLabel(self.centralwidget)
        self.p2_ranged_row9.setText(_fromUtf8(""))
        self.p2_ranged_row9.setObjectName(_fromUtf8("p2_ranged_row9"))
        self.p2_ranged_row.addWidget(self.p2_ranged_row9)
        self.p2_ranged_row10 = QtGui.QLabel(self.centralwidget)
        self.p2_ranged_row10.setText(_fromUtf8(""))
        self.p2_ranged_row10.setObjectName(_fromUtf8("p2_ranged_row10"))
        self.p2_ranged_row.addWidget(self.p2_ranged_row10)
        self.p2_ranged_row11 = QtGui.QLabel(self.centralwidget)
        self.p2_ranged_row11.setText(_fromUtf8(""))
        self.p2_ranged_row11.setObjectName(_fromUtf8("p2_ranged_row11"))
        self.p2_ranged_row.addWidget(self.p2_ranged_row11)
        self.p2_ranged_row12 = QtGui.QLabel(self.centralwidget)
        self.p2_ranged_row12.setText(_fromUtf8(""))
        self.p2_ranged_row12.setObjectName(_fromUtf8("p2_ranged_row12"))
        self.p2_ranged_row.addWidget(self.p2_ranged_row12)
        self.p2_ranged_row13 = QtGui.QLabel(self.centralwidget)
        self.p2_ranged_row13.setText(_fromUtf8(""))
        self.p2_ranged_row13.setObjectName(_fromUtf8("p2_ranged_row13"))
        self.p2_ranged_row.addWidget(self.p2_ranged_row13)
        self.p2_ranged_row14 = QtGui.QLabel(self.centralwidget)
        self.p2_ranged_row14.setText(_fromUtf8(""))
        self.p2_ranged_row14.setObjectName(_fromUtf8("p2_ranged_row14"))
        self.p2_ranged_row.addWidget(self.p2_ranged_row14)
        self.p2_ranged_row15 = QtGui.QLabel(self.centralwidget)
        self.p2_ranged_row15.setText(_fromUtf8(""))
        self.p2_ranged_row15.setObjectName(_fromUtf8("p2_ranged_row15"))
        self.p2_ranged_row.addWidget(self.p2_ranged_row15)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.p2_ranged_row.addItem(spacerItem3)
        self.card_area.addLayout(self.p2_ranged_row)
        self.line_6 = QtGui.QFrame(self.centralwidget)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.card_area.addWidget(self.line_6)
        self.p2_melee_row = QtGui.QHBoxLayout()
        self.p2_melee_row.setObjectName(_fromUtf8("p2_melee_row"))
        self.p2_melee_score_text = QtGui.QLabel(self.centralwidget)
        self.p2_melee_score_text.setObjectName(_fromUtf8("p2_melee_score_text"))
        self.p2_melee_row.addWidget(self.p2_melee_score_text)
        self.line_11 = QtGui.QFrame(self.centralwidget)
        self.line_11.setMinimumSize(QtCore.QSize(0, 50))
        self.line_11.setFrameShape(QtGui.QFrame.VLine)
        self.line_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_11.setObjectName(_fromUtf8("line_11"))
        self.p2_melee_row.addWidget(self.line_11)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.p2_melee_row.addItem(spacerItem4)
        self.p2_melee_row1 = QtGui.QLabel(self.centralwidget)
        self.p2_melee_row1.setText(_fromUtf8(""))
        self.p2_melee_row1.setObjectName(_fromUtf8("p2_melee_row1"))
        self.p2_melee_row.addWidget(self.p2_melee_row1)
        self.p2_melee_row2 = QtGui.QLabel(self.centralwidget)
        self.p2_melee_row2.setText(_fromUtf8(""))
        self.p2_melee_row2.setObjectName(_fromUtf8("p2_melee_row2"))
        self.p2_melee_row.addWidget(self.p2_melee_row2)
        self.p2_melee_row3 = QtGui.QLabel(self.centralwidget)
        self.p2_melee_row3.setText(_fromUtf8(""))
        self.p2_melee_row3.setObjectName(_fromUtf8("p2_melee_row3"))
        self.p2_melee_row.addWidget(self.p2_melee_row3)
        self.p2_melee_row4 = QtGui.QLabel(self.centralwidget)
        self.p2_melee_row4.setText(_fromUtf8(""))
        self.p2_melee_row4.setObjectName(_fromUtf8("p2_melee_row4"))
        self.p2_melee_row.addWidget(self.p2_melee_row4)
        self.p2_melee_row5 = QtGui.QLabel(self.centralwidget)
        self.p2_melee_row5.setText(_fromUtf8(""))
        self.p2_melee_row5.setObjectName(_fromUtf8("p2_melee_row5"))
        self.p2_melee_row.addWidget(self.p2_melee_row5)
        self.p2_melee_row6 = QtGui.QLabel(self.centralwidget)
        self.p2_melee_row6.setText(_fromUtf8(""))
        self.p2_melee_row6.setObjectName(_fromUtf8("p2_melee_row6"))
        self.p2_melee_row.addWidget(self.p2_melee_row6)
        self.p2_melee_row7 = QtGui.QLabel(self.centralwidget)
        self.p2_melee_row7.setText(_fromUtf8(""))
        self.p2_melee_row7.setObjectName(_fromUtf8("p2_melee_row7"))
        self.p2_melee_row.addWidget(self.p2_melee_row7)
        self.p2_melee_row8 = QtGui.QLabel(self.centralwidget)
        self.p2_melee_row8.setText(_fromUtf8(""))
        self.p2_melee_row8.setObjectName(_fromUtf8("p2_melee_row8"))
        self.p2_melee_row.addWidget(self.p2_melee_row8)
        self.p2_melee_row9 = QtGui.QLabel(self.centralwidget)
        self.p2_melee_row9.setText(_fromUtf8(""))
        self.p2_melee_row9.setObjectName(_fromUtf8("p2_melee_row9"))
        self.p2_melee_row.addWidget(self.p2_melee_row9)
        self.p2_melee_row10 = QtGui.QLabel(self.centralwidget)
        self.p2_melee_row10.setText(_fromUtf8(""))
        self.p2_melee_row10.setObjectName(_fromUtf8("p2_melee_row10"))
        self.p2_melee_row.addWidget(self.p2_melee_row10)
        self.p2_melee_row11 = QtGui.QLabel(self.centralwidget)
        self.p2_melee_row11.setText(_fromUtf8(""))
        self.p2_melee_row11.setObjectName(_fromUtf8("p2_melee_row11"))
        self.p2_melee_row.addWidget(self.p2_melee_row11)
        self.p2_melee_row12 = QtGui.QLabel(self.centralwidget)
        self.p2_melee_row12.setMinimumSize(QtCore.QSize(0, 0))
        self.p2_melee_row12.setText(_fromUtf8(""))
        self.p2_melee_row12.setObjectName(_fromUtf8("p2_melee_row12"))
        self.p2_melee_row.addWidget(self.p2_melee_row12)
        self.p2_melee_row13 = QtGui.QLabel(self.centralwidget)
        self.p2_melee_row13.setText(_fromUtf8(""))
        self.p2_melee_row13.setObjectName(_fromUtf8("p2_melee_row13"))
        self.p2_melee_row.addWidget(self.p2_melee_row13)
        self.p2_melee_row14 = QtGui.QLabel(self.centralwidget)
        self.p2_melee_row14.setText(_fromUtf8(""))
        self.p2_melee_row14.setObjectName(_fromUtf8("p2_melee_row14"))
        self.p2_melee_row.addWidget(self.p2_melee_row14)
        self.p2_melee_row15 = QtGui.QLabel(self.centralwidget)
        self.p2_melee_row15.setText(_fromUtf8(""))
        self.p2_melee_row15.setObjectName(_fromUtf8("p2_melee_row15"))
        self.p2_melee_row.addWidget(self.p2_melee_row15)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.p2_melee_row.addItem(spacerItem5)
        self.card_area.addLayout(self.p2_melee_row)
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.card_area.addWidget(self.line_2)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.card_area.addWidget(self.line)
        self.p1_melee_row = QtGui.QHBoxLayout()
        self.p1_melee_row.setObjectName(_fromUtf8("p1_melee_row"))
        self.p1_melee_score_text = QtGui.QLabel(self.centralwidget)
        self.p1_melee_score_text.setObjectName(_fromUtf8("p1_melee_score_text"))
        self.p1_melee_row.addWidget(self.p1_melee_score_text)
        self.line_12 = QtGui.QFrame(self.centralwidget)
        self.line_12.setMinimumSize(QtCore.QSize(0, 50))
        self.line_12.setFrameShape(QtGui.QFrame.VLine)
        self.line_12.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_12.setObjectName(_fromUtf8("line_12"))
        self.p1_melee_row.addWidget(self.line_12)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.p1_melee_row.addItem(spacerItem6)
        self.p1_melee_row1 = QtGui.QLabel(self.centralwidget)
        self.p1_melee_row1.setText(_fromUtf8(""))
        self.p1_melee_row1.setObjectName(_fromUtf8("p1_melee_row1"))
        self.p1_melee_row.addWidget(self.p1_melee_row1)
        self.p1_melee_row2 = QtGui.QLabel(self.centralwidget)
        self.p1_melee_row2.setText(_fromUtf8(""))
        self.p1_melee_row2.setObjectName(_fromUtf8("p1_melee_row2"))
        self.p1_melee_row.addWidget(self.p1_melee_row2)
        self.p1_melee_row3 = QtGui.QLabel(self.centralwidget)
        self.p1_melee_row3.setText(_fromUtf8(""))
        self.p1_melee_row3.setObjectName(_fromUtf8("p1_melee_row3"))
        self.p1_melee_row.addWidget(self.p1_melee_row3)
        self.p1_melee_row4 = QtGui.QLabel(self.centralwidget)
        self.p1_melee_row4.setText(_fromUtf8(""))
        self.p1_melee_row4.setObjectName(_fromUtf8("p1_melee_row4"))
        self.p1_melee_row.addWidget(self.p1_melee_row4)
        self.p1_melee_row5 = QtGui.QLabel(self.centralwidget)
        self.p1_melee_row5.setText(_fromUtf8(""))
        self.p1_melee_row5.setObjectName(_fromUtf8("p1_melee_row5"))
        self.p1_melee_row.addWidget(self.p1_melee_row5)
        self.p1_melee_row6 = QtGui.QLabel(self.centralwidget)
        self.p1_melee_row6.setText(_fromUtf8(""))
        self.p1_melee_row6.setObjectName(_fromUtf8("p1_melee_row6"))
        self.p1_melee_row.addWidget(self.p1_melee_row6)
        self.p1_melee_row7 = QtGui.QLabel(self.centralwidget)
        self.p1_melee_row7.setText(_fromUtf8(""))
        self.p1_melee_row7.setObjectName(_fromUtf8("p1_melee_row7"))
        self.p1_melee_row.addWidget(self.p1_melee_row7)
        self.p1_melee_row8 = QtGui.QLabel(self.centralwidget)
        self.p1_melee_row8.setText(_fromUtf8(""))
        self.p1_melee_row8.setObjectName(_fromUtf8("p1_melee_row8"))
        self.p1_melee_row.addWidget(self.p1_melee_row8)
        self.p1_melee_row9 = QtGui.QLabel(self.centralwidget)
        self.p1_melee_row9.setText(_fromUtf8(""))
        self.p1_melee_row9.setObjectName(_fromUtf8("p1_melee_row9"))
        self.p1_melee_row.addWidget(self.p1_melee_row9)
        self.p1_melee_row10 = QtGui.QLabel(self.centralwidget)
        self.p1_melee_row10.setText(_fromUtf8(""))
        self.p1_melee_row10.setObjectName(_fromUtf8("p1_melee_row10"))
        self.p1_melee_row.addWidget(self.p1_melee_row10)
        self.p1_melee_row11 = QtGui.QLabel(self.centralwidget)
        self.p1_melee_row11.setText(_fromUtf8(""))
        self.p1_melee_row11.setObjectName(_fromUtf8("p1_melee_row11"))
        self.p1_melee_row.addWidget(self.p1_melee_row11)
        self.p1_melee_row12 = QtGui.QLabel(self.centralwidget)
        self.p1_melee_row12.setText(_fromUtf8(""))
        self.p1_melee_row12.setObjectName(_fromUtf8("p1_melee_row12"))
        self.p1_melee_row.addWidget(self.p1_melee_row12)
        self.p1_melee_row13 = QtGui.QLabel(self.centralwidget)
        self.p1_melee_row13.setText(_fromUtf8(""))
        self.p1_melee_row13.setObjectName(_fromUtf8("p1_melee_row13"))
        self.p1_melee_row.addWidget(self.p1_melee_row13)
        self.p1_melee_row14 = QtGui.QLabel(self.centralwidget)
        self.p1_melee_row14.setText(_fromUtf8(""))
        self.p1_melee_row14.setObjectName(_fromUtf8("p1_melee_row14"))
        self.p1_melee_row.addWidget(self.p1_melee_row14)
        self.p1_melee_row15 = QtGui.QLabel(self.centralwidget)
        self.p1_melee_row15.setText(_fromUtf8(""))
        self.p1_melee_row15.setObjectName(_fromUtf8("p1_melee_row15"))
        self.p1_melee_row.addWidget(self.p1_melee_row15)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.p1_melee_row.addItem(spacerItem7)
        self.card_area.addLayout(self.p1_melee_row)
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.card_area.addWidget(self.line_3)
        self.p1_ranged_row = QtGui.QHBoxLayout()
        self.p1_ranged_row.setObjectName(_fromUtf8("p1_ranged_row"))
        self.p1_ranged_score_text = QtGui.QLabel(self.centralwidget)
        self.p1_ranged_score_text.setObjectName(_fromUtf8("p1_ranged_score_text"))
        self.p1_ranged_row.addWidget(self.p1_ranged_score_text)
        self.line_13 = QtGui.QFrame(self.centralwidget)
        self.line_13.setMinimumSize(QtCore.QSize(0, 50))
        self.line_13.setFrameShape(QtGui.QFrame.VLine)
        self.line_13.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_13.setObjectName(_fromUtf8("line_13"))
        self.p1_ranged_row.addWidget(self.line_13)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.p1_ranged_row.addItem(spacerItem8)
        self.p1_ranged_row1 = QtGui.QLabel(self.centralwidget)
        self.p1_ranged_row1.setText(_fromUtf8(""))
        self.p1_ranged_row1.setObjectName(_fromUtf8("p1_ranged_row1"))
        self.p1_ranged_row.addWidget(self.p1_ranged_row1)
        self.p1_ranged_row2 = QtGui.QLabel(self.centralwidget)
        self.p1_ranged_row2.setText(_fromUtf8(""))
        self.p1_ranged_row2.setObjectName(_fromUtf8("p1_ranged_row2"))
        self.p1_ranged_row.addWidget(self.p1_ranged_row2)
        self.p1_ranged_row3 = QtGui.QLabel(self.centralwidget)
        self.p1_ranged_row3.setText(_fromUtf8(""))
        self.p1_ranged_row3.setObjectName(_fromUtf8("p1_ranged_row3"))
        self.p1_ranged_row.addWidget(self.p1_ranged_row3)
        self.p1_ranged_row4 = QtGui.QLabel(self.centralwidget)
        self.p1_ranged_row4.setText(_fromUtf8(""))
        self.p1_ranged_row4.setObjectName(_fromUtf8("p1_ranged_row4"))
        self.p1_ranged_row.addWidget(self.p1_ranged_row4)
        self.p1_ranged_row5 = QtGui.QLabel(self.centralwidget)
        self.p1_ranged_row5.setText(_fromUtf8(""))
        self.p1_ranged_row5.setObjectName(_fromUtf8("p1_ranged_row5"))
        self.p1_ranged_row.addWidget(self.p1_ranged_row5)
        self.p1_ranged_row6 = QtGui.QLabel(self.centralwidget)
        self.p1_ranged_row6.setText(_fromUtf8(""))
        self.p1_ranged_row6.setObjectName(_fromUtf8("p1_ranged_row6"))
        self.p1_ranged_row.addWidget(self.p1_ranged_row6)
        self.p1_ranged_row7 = QtGui.QLabel(self.centralwidget)
        self.p1_ranged_row7.setText(_fromUtf8(""))
        self.p1_ranged_row7.setObjectName(_fromUtf8("p1_ranged_row7"))
        self.p1_ranged_row.addWidget(self.p1_ranged_row7)
        self.p1_ranged_row8 = QtGui.QLabel(self.centralwidget)
        self.p1_ranged_row8.setText(_fromUtf8(""))
        self.p1_ranged_row8.setObjectName(_fromUtf8("p1_ranged_row8"))
        self.p1_ranged_row.addWidget(self.p1_ranged_row8)
        self.p1_ranged_row9 = QtGui.QLabel(self.centralwidget)
        self.p1_ranged_row9.setText(_fromUtf8(""))
        self.p1_ranged_row9.setObjectName(_fromUtf8("p1_ranged_row9"))
        self.p1_ranged_row.addWidget(self.p1_ranged_row9)
        self.p1_ranged_row10 = QtGui.QLabel(self.centralwidget)
        self.p1_ranged_row10.setText(_fromUtf8(""))
        self.p1_ranged_row10.setObjectName(_fromUtf8("p1_ranged_row10"))
        self.p1_ranged_row.addWidget(self.p1_ranged_row10)
        self.p1_ranged_row11 = QtGui.QLabel(self.centralwidget)
        self.p1_ranged_row11.setText(_fromUtf8(""))
        self.p1_ranged_row11.setObjectName(_fromUtf8("p1_ranged_row11"))
        self.p1_ranged_row.addWidget(self.p1_ranged_row11)
        self.p1_ranged_row12 = QtGui.QLabel(self.centralwidget)
        self.p1_ranged_row12.setText(_fromUtf8(""))
        self.p1_ranged_row12.setObjectName(_fromUtf8("p1_ranged_row12"))
        self.p1_ranged_row.addWidget(self.p1_ranged_row12)
        self.p1_ranged_row13 = QtGui.QLabel(self.centralwidget)
        self.p1_ranged_row13.setText(_fromUtf8(""))
        self.p1_ranged_row13.setObjectName(_fromUtf8("p1_ranged_row13"))
        self.p1_ranged_row.addWidget(self.p1_ranged_row13)
        self.p1_ranged_row14 = QtGui.QLabel(self.centralwidget)
        self.p1_ranged_row14.setText(_fromUtf8(""))
        self.p1_ranged_row14.setObjectName(_fromUtf8("p1_ranged_row14"))
        self.p1_ranged_row.addWidget(self.p1_ranged_row14)
        self.p1_ranged_row15 = QtGui.QLabel(self.centralwidget)
        self.p1_ranged_row15.setText(_fromUtf8(""))
        self.p1_ranged_row15.setObjectName(_fromUtf8("p1_ranged_row15"))
        self.p1_ranged_row.addWidget(self.p1_ranged_row15)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.p1_ranged_row.addItem(spacerItem9)
        self.card_area.addLayout(self.p1_ranged_row)
        self.line_4 = QtGui.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.card_area.addWidget(self.line_4)
        self.p1_siege_row = QtGui.QHBoxLayout()
        self.p1_siege_row.setObjectName(_fromUtf8("p1_siege_row"))
        self.p1_siege_score_text = QtGui.QLabel(self.centralwidget)
        self.p1_siege_score_text.setObjectName(_fromUtf8("p1_siege_score_text"))
        self.p1_siege_row.addWidget(self.p1_siege_score_text)
        self.line_14 = QtGui.QFrame(self.centralwidget)
        self.line_14.setMinimumSize(QtCore.QSize(0, 50))
        self.line_14.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.line_14.setFrameShape(QtGui.QFrame.VLine)
        self.line_14.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_14.setObjectName(_fromUtf8("line_14"))
        self.p1_siege_row.addWidget(self.line_14)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.p1_siege_row.addItem(spacerItem10)
        self.p1_siege_row1 = QtGui.QLabel(self.centralwidget)
        self.p1_siege_row1.setText(_fromUtf8(""))
        self.p1_siege_row1.setObjectName(_fromUtf8("p1_siege_row1"))
        self.p1_siege_row.addWidget(self.p1_siege_row1)
        self.p1_siege_row2 = QtGui.QLabel(self.centralwidget)
        self.p1_siege_row2.setText(_fromUtf8(""))
        self.p1_siege_row2.setObjectName(_fromUtf8("p1_siege_row2"))
        self.p1_siege_row.addWidget(self.p1_siege_row2)
        self.p1_siege_row3 = QtGui.QLabel(self.centralwidget)
        self.p1_siege_row3.setText(_fromUtf8(""))
        self.p1_siege_row3.setObjectName(_fromUtf8("p1_siege_row3"))
        self.p1_siege_row.addWidget(self.p1_siege_row3)
        self.p1_siege_row4 = QtGui.QLabel(self.centralwidget)
        self.p1_siege_row4.setText(_fromUtf8(""))
        self.p1_siege_row4.setObjectName(_fromUtf8("p1_siege_row4"))
        self.p1_siege_row.addWidget(self.p1_siege_row4)
        self.p1_siege_row5 = QtGui.QLabel(self.centralwidget)
        self.p1_siege_row5.setText(_fromUtf8(""))
        self.p1_siege_row5.setObjectName(_fromUtf8("p1_siege_row5"))
        self.p1_siege_row.addWidget(self.p1_siege_row5)
        self.p1_siege_row6 = QtGui.QLabel(self.centralwidget)
        self.p1_siege_row6.setText(_fromUtf8(""))
        self.p1_siege_row6.setObjectName(_fromUtf8("p1_siege_row6"))
        self.p1_siege_row.addWidget(self.p1_siege_row6)
        self.p1_siege_row7 = QtGui.QLabel(self.centralwidget)
        self.p1_siege_row7.setText(_fromUtf8(""))
        self.p1_siege_row7.setObjectName(_fromUtf8("p1_siege_row7"))
        self.p1_siege_row.addWidget(self.p1_siege_row7)
        self.p1_siege_row8 = QtGui.QLabel(self.centralwidget)
        self.p1_siege_row8.setText(_fromUtf8(""))
        self.p1_siege_row8.setObjectName(_fromUtf8("p1_siege_row8"))
        self.p1_siege_row.addWidget(self.p1_siege_row8)
        self.p1_siege_row9 = QtGui.QLabel(self.centralwidget)
        self.p1_siege_row9.setText(_fromUtf8(""))
        self.p1_siege_row9.setObjectName(_fromUtf8("p1_siege_row9"))
        self.p1_siege_row.addWidget(self.p1_siege_row9)
        self.p1_siege_row10 = QtGui.QLabel(self.centralwidget)
        self.p1_siege_row10.setText(_fromUtf8(""))
        self.p1_siege_row10.setObjectName(_fromUtf8("p1_siege_row10"))
        self.p1_siege_row.addWidget(self.p1_siege_row10)
        self.p1_siege_row11 = QtGui.QLabel(self.centralwidget)
        self.p1_siege_row11.setText(_fromUtf8(""))
        self.p1_siege_row11.setObjectName(_fromUtf8("p1_siege_row11"))
        self.p1_siege_row.addWidget(self.p1_siege_row11)
        self.p1_siege_row12 = QtGui.QLabel(self.centralwidget)
        self.p1_siege_row12.setText(_fromUtf8(""))
        self.p1_siege_row12.setObjectName(_fromUtf8("p1_siege_row12"))
        self.p1_siege_row.addWidget(self.p1_siege_row12)
        self.p1_siege_row13 = QtGui.QLabel(self.centralwidget)
        self.p1_siege_row13.setText(_fromUtf8(""))
        self.p1_siege_row13.setObjectName(_fromUtf8("p1_siege_row13"))
        self.p1_siege_row.addWidget(self.p1_siege_row13)
        self.p1_siege_row14 = QtGui.QLabel(self.centralwidget)
        self.p1_siege_row14.setText(_fromUtf8(""))
        self.p1_siege_row14.setObjectName(_fromUtf8("p1_siege_row14"))
        self.p1_siege_row.addWidget(self.p1_siege_row14)
        self.p1_siege_row15 = QtGui.QLabel(self.centralwidget)
        self.p1_siege_row15.setText(_fromUtf8(""))
        self.p1_siege_row15.setObjectName(_fromUtf8("p1_siege_row15"))
        self.p1_siege_row.addWidget(self.p1_siege_row15)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.p1_siege_row.addItem(spacerItem11)
        self.card_area.addLayout(self.p1_siege_row)
        self.board.addLayout(self.card_area)
        self.verticalLayout.addLayout(self.board)
        self.line_5 = QtGui.QFrame(self.centralwidget)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.verticalLayout.addWidget(self.line_5)
        self.hand = QtGui.QHBoxLayout()
        self.hand.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.hand.setObjectName(_fromUtf8("hand"))
        self.line_15 = QtGui.QFrame(self.centralwidget)
        self.line_15.setMinimumSize(QtCore.QSize(0, 100))
        self.line_15.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.line_15.setFrameShape(QtGui.QFrame.VLine)
        self.line_15.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_15.setObjectName(_fromUtf8("line_15"))
        self.hand.addWidget(self.line_15)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hand.addItem(spacerItem12)
        self.hand_1 = QtGui.QLabel(self.centralwidget)
        self.hand_1.setToolTip(_fromUtf8(""))
        self.hand_1.setText(_fromUtf8(""))
        self.hand_1.setAlignment(QtCore.Qt.AlignCenter)
        self.hand_1.setObjectName(_fromUtf8("hand_1"))
        self.hand.addWidget(self.hand_1)
        self.hand_2 = QtGui.QLabel(self.centralwidget)
        self.hand_2.setText(_fromUtf8(""))
        self.hand_2.setAlignment(QtCore.Qt.AlignCenter)
        self.hand_2.setObjectName(_fromUtf8("hand_2"))
        self.hand.addWidget(self.hand_2)
        self.hand_3 = QtGui.QLabel(self.centralwidget)
        self.hand_3.setText(_fromUtf8(""))
        self.hand_3.setAlignment(QtCore.Qt.AlignCenter)
        self.hand_3.setObjectName(_fromUtf8("hand_3"))
        self.hand.addWidget(self.hand_3)
        self.hand_4 = QtGui.QLabel(self.centralwidget)
        self.hand_4.setText(_fromUtf8(""))
        self.hand_4.setAlignment(QtCore.Qt.AlignCenter)
        self.hand_4.setObjectName(_fromUtf8("hand_4"))
        self.hand.addWidget(self.hand_4)
        self.hand_5 = QtGui.QLabel(self.centralwidget)
        self.hand_5.setText(_fromUtf8(""))
        self.hand_5.setAlignment(QtCore.Qt.AlignCenter)
        self.hand_5.setObjectName(_fromUtf8("hand_5"))
        self.hand.addWidget(self.hand_5)
        self.hand_6 = QtGui.QLabel(self.centralwidget)
        self.hand_6.setText(_fromUtf8(""))
        self.hand_6.setAlignment(QtCore.Qt.AlignCenter)
        self.hand_6.setObjectName(_fromUtf8("hand_6"))
        self.hand.addWidget(self.hand_6)
        self.hand_7 = QtGui.QLabel(self.centralwidget)
        self.hand_7.setText(_fromUtf8(""))
        self.hand_7.setAlignment(QtCore.Qt.AlignCenter)
        self.hand_7.setObjectName(_fromUtf8("hand_7"))
        self.hand.addWidget(self.hand_7)
        self.hand_8 = QtGui.QLabel(self.centralwidget)
        self.hand_8.setText(_fromUtf8(""))
        self.hand_8.setAlignment(QtCore.Qt.AlignCenter)
        self.hand_8.setObjectName(_fromUtf8("hand_8"))
        self.hand.addWidget(self.hand_8)
        self.hand_9 = QtGui.QLabel(self.centralwidget)
        self.hand_9.setText(_fromUtf8(""))
        self.hand_9.setAlignment(QtCore.Qt.AlignCenter)
        self.hand_9.setObjectName(_fromUtf8("hand_9"))
        self.hand.addWidget(self.hand_9)
        self.hand_10 = QtGui.QLabel(self.centralwidget)
        self.hand_10.setText(_fromUtf8(""))
        self.hand_10.setAlignment(QtCore.Qt.AlignCenter)
        self.hand_10.setObjectName(_fromUtf8("hand_10"))
        self.hand.addWidget(self.hand_10)
        self.hand_11 = QtGui.QLabel(self.centralwidget)
        self.hand_11.setText(_fromUtf8(""))
        self.hand_11.setAlignment(QtCore.Qt.AlignCenter)
        self.hand_11.setObjectName(_fromUtf8("hand_11"))
        self.hand.addWidget(self.hand_11)
        self.hand_12 = QtGui.QLabel(self.centralwidget)
        self.hand_12.setText(_fromUtf8(""))
        self.hand_12.setAlignment(QtCore.Qt.AlignCenter)
        self.hand_12.setObjectName(_fromUtf8("hand_12"))
        self.hand.addWidget(self.hand_12)
        self.hand_13 = QtGui.QLabel(self.centralwidget)
        self.hand_13.setText(_fromUtf8(""))
        self.hand_13.setAlignment(QtCore.Qt.AlignCenter)
        self.hand_13.setObjectName(_fromUtf8("hand_13"))
        self.hand.addWidget(self.hand_13)
        self.hand_14 = QtGui.QLabel(self.centralwidget)
        self.hand_14.setText(_fromUtf8(""))
        self.hand_14.setAlignment(QtCore.Qt.AlignCenter)
        self.hand_14.setObjectName(_fromUtf8("hand_14"))
        self.hand.addWidget(self.hand_14)
        self.hand_15 = QtGui.QLabel(self.centralwidget)
        self.hand_15.setText(_fromUtf8(""))
        self.hand_15.setAlignment(QtCore.Qt.AlignCenter)
        self.hand_15.setObjectName(_fromUtf8("hand_15"))
        self.hand.addWidget(self.hand_15)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hand.addItem(spacerItem13)
        self.line_16 = QtGui.QFrame(self.centralwidget)
        self.line_16.setFrameShape(QtGui.QFrame.VLine)
        self.line_16.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_16.setObjectName(_fromUtf8("line_16"))
        self.hand.addWidget(self.line_16)
        self.verticalLayout.addLayout(self.hand)
        self.line_17 = QtGui.QFrame(self.centralwidget)
        self.line_17.setFrameShape(QtGui.QFrame.HLine)
        self.line_17.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_17.setObjectName(_fromUtf8("line_17"))
        self.verticalLayout.addWidget(self.line_17)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Jwent", None))
        self.p2_score_text.setText(_translate("MainWindow", "0", None))
        self.p1_score_text.setText(_translate("MainWindow", "0", None))
        self.p2_siege_score_text.setText(_translate("MainWindow", "0", None))
        self.p2_ranged_score_text.setText(_translate("MainWindow", "0", None))
        self.p2_melee_score_text.setText(_translate("MainWindow", "0", None))
        self.p1_melee_score_text.setText(_translate("MainWindow", "0", None))
        self.p1_ranged_score_text.setText(_translate("MainWindow", "0", None))
        self.p1_siege_score_text.setText(_translate("MainWindow", "0", None))

